## REL has DEF

In [1]:
import pandas as pd

umls_def = pd.read_csv('UMLS_DEF.csv')
umls_doc = pd.read_csv('UMLS_DOC.csv')
umls_rel = pd.read_csv('UMLS_REL.csv').drop_duplicates()
umls_def.shape, umls_doc.shape

((244911, 3), (907, 2))

In [2]:
umls_rel = pd.merge(umls_rel, umls_def, left_on='CUI1', right_on='cui', how='left')
umls_rel = pd.merge(umls_rel, umls_def, left_on='CUI2', right_on='cui', how='left')
umls_rel = umls_rel.dropna()
umls_rel

,CUI1,REL,CUI2,cui_x,name_x,definition_x,cui_y,name_y,definition_y
1,C0000039,AQ,C0001555,C0000039,"DPPC, Phosphatidylcholine, Dipalmitoyl, Dipalm...",Synthetic phospholipid used in liposomes and l...,C0001555,"administration & dosage, administration and do...","Used with drugs for dosage forms, routes of ad..."
2,C0000039,AQ,C0001688,C0000039,"DPPC, Phosphatidylcholine, Dipalmitoyl, Dipalm...",Synthetic phospholipid used in liposomes and l...,C0001688,"ADV EFF, side effects, aspects of adverse effe...","Used with drugs, chemicals, or biological agen..."
3,C0000039,AQ,C0002776,C0000039,"DPPC, Phosphatidylcholine, Dipalmitoyl, Dipalm...",Synthetic phospholipid used in liposomes and l...,C0002776,"analogs & derivatives, analogs and derivatives...",Used with drugs and chemicals for substances t...
4,C0000039,AQ,C0003139,C0000039,"DPPC, Phosphatidylcholine, Dipalmitoyl, Dipalm...",Synthetic phospholipid used in liposomes and l...,C0003139,"antagonists & inhibitors, AI, inhibitor/antago...","Used with chemicals, drugs, and endogenous sub..."
5,C0000039,AQ,C0005572,C0000039,"DPPC, Phosphatidylcholine, Dipalmitoyl, Dipalm...",Synthetic phospholipid used in liposomes and l...,C0005572,"BIOSYN, bioformation, anabolism, BI, biosynthesis",Used for the anabolic formation of chemical su...
...,...,...,...,...,...,...,...,...,...
20592989,C5847615,RO,C0443146,C5847615,"Diabetes mellitus type 1 stage 2, Diabetes mel...",Includes individuals with two or more islet au...,C0443146,"Autoimmune, autoimmune responses, Autoimmune R...",A specific humoral or cell-mediated immune res...
20593021,C5847622,PAR,C0011854,C5847622,"Diabetes mellitus type 1 stage 3, Diabetes mel...",Represents manifestations of the typical clini...,C0011854,"Diabetes mellitus - juvenile, Juvenile diabete...","<p><a href=""https://medlineplus.gov/diabetes.h..."
20593022,C5847622,PAR,C0271650,C5847622,"Diabetes mellitus type 1 stage 3, Diabetes mel...",Represents manifestations of the typical clini...,C0271650,"glucose intolerance, Glucose Tolerances, Impai...",The inability to regulate blood glucose levels...
20593025,C5847622,RO,C0014136,C5847622,"Diabetes mellitus type 1 stage 3, Diabetes mel...",Represents manifestations of the typical clini...,C0014136,"Endocrine System, Endocrine system structure, ...",Collective designation for those tissues capab...
20593026,C5847622,RO,C0443146,C5847622,"Diabetes mellitus type 1 stage 3, Diabetes mel...",Represents manifestations of the typical clini...,C0443146,"Autoimmune, autoimmune responses, Autoimmune R...",A specific humoral or cell-mediated immune res...

#### Statistics

In [3]:
umls_rel.describe()

,CUI1,REL,CUI2,cui_x,name_x,definition_x,cui_y,name_y,definition_y
count,4083088,4083088,4083088,4083088,4083088,4083088,4083088,4083088,4083088
unique,239303,9,239303,239303,239303,231412,239303,239303,231412
top,C1880104,RO,C1880104,C1880104,"CDISC Terminology, CDISC, Clinical Data Interc...",The terminology that includes terms relevant t...,C1880104,"CDISC Terminology, CDISC, Clinical Data Interc...",The terminology that includes terms relevant t...
freq,27346,1890290,27346,27346,27346,27346,27346,27346,27346

## Save unique entities and relations

In [16]:
import pickle
import pandas as pd

umls_rel = pd.read_csv('UMLS_REL+RELA/UMLS_REL_hasDEF_nor20.csv')
unique_items = umls_rel['REL'].unique().tolist()
with open('UMLS_REL+RELA/REL', 'wb') as fp:
    pickle.dump(unique_items, fp)

unique_items1 = umls_rel['CUI1'].unique().tolist()
unique_items2 = umls_rel['CUI2'].unique().tolist()
print(len(unique_items2))
unique_items = list(set(unique_items1 + unique_items2))
print(len(unique_items))
with open('UMLS_REL+RELA/CUI', 'wb') as fp:
    pickle.dump(unique_items, fp)

224043
236066

#### Encode REL

In [17]:
import pickle
import pandas as pd
from tqdm import tqdm

umls_rel = pd.read_csv('UMLS_REL+RELA/UMLS_REL_hasDEF_nor20.csv')
with open('UMLS_REL+RELA/REL', 'rb') as fp:
    relation_list = pickle.load(fp)

for i, row in tqdm(umls_rel.iterrows()):
    row['REL'] = relation_list.index(row['REL'])
umls_rel

1859292it [01:35, 19521.46it/s]

             CUI1 REL      CUI2
0        C0000039   0  C0001555
1        C0000039   0  C0001688
2        C0000039   0  C0002776
3        C0000039   0  C0003139
4        C0000039   0  C0005572
...           ...  ..       ...
1859287  C5828584   2  C1615053
1859288  C5828614   3  C3658315
1859289  C5847614   6  C0014136
1859290  C5847615   6  C0014136
1859291  C5847622   6  C0014136

[1859292 rows x 3 columns]

#### Add Negative Samples

In [18]:
import random
from tqdm import tqdm

with open('UMLS_REL+RELA/CUI', 'rb') as fp:
    entity_list = pickle.load(fp)
group = umls_rel.groupby('CUI1')['CUI2'].apply(set).reset_index()

pointer = 0
neg_tail_list = []
for i, row in tqdm(umls_rel.iterrows()):
    # align head
    if row['CUI1'] != group['CUI1'][pointer]:
        pointer += 1
    # randomly choose negative tail
    neg_tail = random.choice(entity_list)
    while neg_tail in group['CUI2'][pointer]:
        neg_tail = random.choice(entity_list)
    # add negative tail to the list
    neg_tail_list.append(neg_tail)

len(neg_tail_list)

1859292it [01:46, 17463.43it/s]

1859292

In [19]:
umls_rel['neg_CUI2'] = neg_tail_list
umls_rel.describe()

             CUI1 REL      CUI2  neg_CUI2
0        C0000039   0  C0001555  C1709108
1        C0000039   0  C0001688  C4687345
2        C0000039   0  C0002776  C5558399
3        C0000039   0  C0003139  C0162758
4        C0000039   0  C0005572  C0281642
...           ...  ..       ...       ...
1859287  C5828584   2  C1615053  C0110666
1859288  C5828614   3  C3658315  C0346251
1859289  C5847614   6  C0014136  C1336200
1859290  C5847615   6  C0014136  C4280692
1859291  C5847622   6  C0014136  C1453694

[1859292 rows x 4 columns]

#### Replace CUI with DEF

In [20]:
umls_def = pd.read_csv('UMLS_DEF.csv')[['cui', 'definition']]
umls_rel = pd.merge(umls_rel, umls_def, left_on='CUI1', right_on='cui', how='left')
umls_rel = pd.merge(umls_rel, umls_def, left_on='CUI2', right_on='cui', how='left')
umls_rel = pd.merge(umls_rel, umls_def, left_on='neg_CUI2', right_on='cui', how='left')
umls_rel

,CUI1,REL,CUI2,neg_CUI2,cui_x,definition_x,cui_y,definition_y,cui,definition
0,C0000039,0,C0001555,C1709108,C0000039,Synthetic phospholipid used in liposomes and l...,C0001555,"Used with drugs for dosage forms, routes of ad...",C1709108,A general term that refers to a TNM finding of...
1,C0000039,0,C0001688,C4687345,C0000039,Synthetic phospholipid used in liposomes and l...,C0001688,"Used with drugs, chemicals, or biological agen...",C4687345,Death
2,C0000039,0,C0002776,C5558399,C0000039,Synthetic phospholipid used in liposomes and l...,C0002776,Used with drugs and chemicals for substances t...,C5558399,Abnormally low blood oxygen level without the ...
3,C0000039,0,C0003139,C0162758,C0000039,Synthetic phospholipid used in liposomes and l...,C0003139,"Used with chemicals, drugs, and endogenous sub...",C0162758,Compounds that specifically inhibit the reupta...
4,C0000039,0,C0005572,C0281642,C0000039,Synthetic phospholipid used in liposomes and l...,C0005572,Used for the anabolic formation of chemical su...,C0281642,An acute myeloid leukemia with minimal differe...
...,...,...,...,...,...,...,...,...,...,...
1859287,C5828584,2,C1615053,C0110666,C5828584,"A non-human influenza virus strain, which norm...",C1615053,A subtype of INFLUENZA A VIRUS comprised of th...,C0110666,A derivative of the original MOPP regimen cons...
1859288,C5828614,3,C3658315,C0346251,C5828614,Health effects associated with activities of b...,C3658315,"The conditions in which people are born, grow,...",C0346251,A sarcoma that arises from the kidney.
1859289,C5847614,6,C0014136,C1336200,C5847614,Represents individuals who have developed two ...,C0014136,Collective designation for those tissues capab...,C1336200,"Stage IIC includes: T2c, N0, M0. T2c: Pelvic e..."
1859290,C5847615,6,C0014136,C4280692,C5847615,Includes individuals with two or more islet au...,C0014136,Collective designation for those tissues capab...,C4280692,A deviation in the size of nasopharyngeal aden...
1859291,C5847622,6,C0014136,C1453694,C5847622,Represents manifestations of the typical clini...,C0014136,Collective designation for those tissues capab...,C1453694,"Solute carrier family 22 member 2 (555 aa, ~63..."

In [21]:
umls_rel = umls_rel[['definition_x', 'REL', 'definition_y', 'definition']]
umls_rel = umls_rel.rename(columns={'definition_x': 'CUI1', 'definition_y': 'CUI2', 'definition': 'neg_CUI2'})
umls_rel

,CUI1,REL,CUI2,neg_CUI2
0,Synthetic phospholipid used in liposomes and l...,0,"Used with drugs for dosage forms, routes of ad...",A general term that refers to a TNM finding of...
1,Synthetic phospholipid used in liposomes and l...,0,"Used with drugs, chemicals, or biological agen...",Death
2,Synthetic phospholipid used in liposomes and l...,0,Used with drugs and chemicals for substances t...,Abnormally low blood oxygen level without the ...
3,Synthetic phospholipid used in liposomes and l...,0,"Used with chemicals, drugs, and endogenous sub...",Compounds that specifically inhibit the reupta...
4,Synthetic phospholipid used in liposomes and l...,0,Used for the anabolic formation of chemical su...,An acute myeloid leukemia with minimal differe...
...,...,...,...,...
1859287,"A non-human influenza virus strain, which norm...",2,A subtype of INFLUENZA A VIRUS comprised of th...,A derivative of the original MOPP regimen cons...
1859288,Health effects associated with activities of b...,3,"The conditions in which people are born, grow,...",A sarcoma that arises from the kidney.
1859289,Represents individuals who have developed two ...,6,Collective designation for those tissues capab...,"Stage IIC includes: T2c, N0, M0. T2c: Pelvic e..."
1859290,Includes individuals with two or more islet au...,6,Collective designation for those tissues capab...,A deviation in the size of nasopharyngeal aden...
1859291,Represents manifestations of the typical clini...,6,Collective designation for those tissues capab...,"Solute carrier family 22 member 2 (555 aa, ~63..."

In [22]:
umls_rel.to_csv('UMLS_REL+RELA/UMLS_REL_allDEF_nor20.csv', index=False)

In [23]:
umls_rel.describe()

,CUI1,REL,CUI2,neg_CUI2
count,1859292,1859292,1859292,1859292
unique,132256,20,217126,228167
top,The terminology that includes terms relevant t...,0,Used for taxonomic or other systematic or hier...,Death
freq,27345,624581,25160,3643

#### Remove Reverse Relations + Cut Data

In [1]:
import pandas as pd

umls_rel = pd.read_csv('UMLS_REL+RELA/UMLS_REL_hasDEF.csv')
group = umls_rel.groupby('REL').size().reset_index(name='Count').sort_values(by='Count', ascending=False, ignore_index=True)
group

                                REL   Count
0                                AQ  624581
1                                QB  624581
2                 concept_in_subset  320620
3           subset_includes_concept  320620
4                               isa  317575
..                              ...     ...
675            surgical_approach_of       1
676                     larger_than       1
677    procedure_has_imaged_anatomy       1
678  has_specimen_source_morphology       1
679                  germ_origin_of       1

[680 rows x 2 columns]

In [2]:
rel_list = []
for i in range(0, len(group)):
    if i == 0:
        rel_list.append(group['REL'][i])
        continue
    if group['Count'][i] != group['Count'][i - 1]:
        rel_list.append(group['REL'][i])
len(rel_list)

247

In [3]:
new_umls_rel = umls_rel[umls_rel['REL'].isin(rel_list)]
new_umls_rel.describe()

            CUI1      REL      CUI2
count    2163988  2163988   2163988
unique    162706      247    226582
top     C1880104       AQ  C0008903
freq       27345   624581     25160

In [4]:
new_group = new_umls_rel.groupby('REL').size().reset_index(name='Count').sort_values(by='Count', ascending=False, ignore_index=True)
new_group

                                                   REL   Count
0                                                   AQ  624581
1                                    concept_in_subset  320620
2                                                  isa  317575
3                                                   RO  114102
4                                                  PAR   72262
..                                                 ...     ...
242                             has_specimen_procedure       5
243                               has_owning_affiliate       4
244  chemical_or_drug_metabolism_is_associated_with...       3
245             chemical_or_drug_affects_abnormal_cell       2
246                                    has_germ_origin       1

[247 rows x 2 columns]

In [14]:
selected_rows = new_umls_rel[new_umls_rel['REL'].isin(new_group['REL'][:20])]
unique_items1 = selected_rows['CUI1'].unique().tolist()
unique_items2 = selected_rows['CUI2'].unique().tolist()
unique_items = list(set(unique_items1 + unique_items2))
print(len(unique_items))
selected_rows.describe()

236066

            CUI1      REL      CUI2
count    1859292  1859292   1859292
unique    136461       20    224043
top     C1880104       AQ  C0008903
freq       27345   624581     25160

In [15]:
selected_rows.to_csv('UMLS_REL+RELA/UMLS_REL_hasDEF_nor20.csv', index=False)

In [13]:
import numpy as np

arr = np.load('weights/KG_000.npy')
arr.shape

(1024, 3, 768)

In [15]:
arr1 = np.load('weights/KG_avg_001.npy')
arr1.shape

(1024, 768)

#### generate posDEF

In [1]:
import pandas as pd
import pickle

with open('pickle_relation', 'rb') as fp:
    relation_list = pickle.load(fp)
data_df = pd.read_csv('UMLS_REL+RELA/UMLS_REL_allDEF.csv')[['CUI1', 'REL', 'CUI2']]
doc_df = pd.read_csv('UMLS_DOC.csv').dropna()
doc_df['EXPL'] = doc_df['EXPL'].str.replace('_', ' ')
doc_df['EXPL'] = doc_df['EXPL'].str.lower()

In [2]:
from tqdm import tqdm

for i, row in tqdm(data_df.iterrows()):
    rel = doc_df[doc_df['VALUE'].str.contains(relation_list[row['REL']])].iloc[0]['EXPL']
    data_df.loc[i, 'REL'] = rel
data_df

0it [00:00, ?it/s]C:\Users\wxc\AppData\Local\Temp\ipykernel_27412\585836826.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'allowed qualifier' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_df.loc[i, 'REL'] = rel
4206228it [41:50, 1675.77it/s]

,CUI1,REL,CUI2
0,Synthetic phospholipid used in liposomes and l...,allowed qualifier,"Used with drugs for dosage forms, routes of ad..."
1,Synthetic phospholipid used in liposomes and l...,allowed qualifier,"Used with drugs, chemicals, or biological agen..."
2,Synthetic phospholipid used in liposomes and l...,allowed qualifier,Used with drugs and chemicals for substances t...
3,Synthetic phospholipid used in liposomes and l...,allowed qualifier,"Used with chemicals, drugs, and endogenous sub..."
4,Synthetic phospholipid used in liposomes and l...,allowed qualifier,Used for the anabolic formation of chemical su...
...,...,...,...
4206223,Includes individuals with two or more islet au...,pathological process of,A specific humoral or cell-mediated immune res...
4206224,Represents manifestations of the typical clini...,inverse is a,"<p><a href=""https://medlineplus.gov/diabetes.h..."
4206225,Represents manifestations of the typical clini...,inverse is a,The inability to regulate blood glucose levels...
4206226,Represents manifestations of the typical clini...,finding site of,Collective designation for those tissues capab...
4206227,Represents manifestations of the typical clini...,pathological process of,A specific humoral or cell-mediated immune res...

In [3]:
data_df.to_csv('UMLS_REL+RELA/UMLS_REL_posDEF.csv', index=False)

In [5]:
data_df['CUI1'][:10].tolist()

['Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.']

In [1]:
import pickle

with open('pickle_relation_id', 'rb') as fp:
    relation_id_list = pickle.load(fp)
with open('pickle_entity_id', 'rb') as fp:
    entity_id_list = pickle.load(fp)
print(len(relation_id_list))
print(len(entity_id_list))

680
239303

In [2]:
import pandas as pd

def_df = pd.read_csv('UMLS_DEF.csv')
doc_df = pd.read_csv('UMLS_DOC.csv').dropna()
doc_df['EXPL'] = doc_df['EXPL'].str.replace('_', ' ')
doc_df['EXPL'] = doc_df['EXPL'].str.lower()

In [14]:
from tqdm import tqdm
relation_list, entity_list = [], []
for rel_id in tqdm(relation_id_list):
    rel = doc_df[doc_df['VALUE'].str.contains(rel_id)].iloc[0]['EXPL']
    relation_list.append(rel)

i = 0
for ent_id in tqdm(entity_id_list):
    for j in range(i, len(def_df)):
        if ent_id == def_df['cui'][j]:
            entity_list.append(def_df['definition'][j])
            i = j
            break

100%|██████████| 680/680 [00:00<00:00, 2023.81it/s]
100%|██████████| 239303/239303 [00:02<00:00, 88156.81it/s]

In [25]:
with open('pickle_relation', 'wb') as fp:
    pickle.dump(relation_list, fp)
with open('pickle_entity', 'wb') as fp:
    pickle.dump(entity_list, fp)

In [3]:
import pandas as pd
a = pd.read_csv('UMLS_REL+RELA/UMLS_REL_all.csv')
a

             CUI1  REL      CUI2  neg_CUI2
0        C0000039    0  C0001555  C2987321
1        C0000039    0  C0001688  C0243009
2        C0000039    0  C0002776  C1555573
3        C0000039    0  C0003139  C1334239
4        C0000039    0  C0005572  C0999515
...           ...  ...       ...       ...
4206223  C5847615   68  C0443146  C4749431
4206224  C5847622    3  C0011854  C1553689
4206225  C5847622    3  C0271650  C0238547
4206226  C5847622   60  C0014136  C1422661
4206227  C5847622   68  C0443146  C3829796

[4206228 rows x 4 columns]

#### retrieve

In [1]:
import numpy as np
import pandas as pd

topk_idx_img = np.load('topk_idx/topk_idx_img_PC_avg_IVFPQ_pca.npy')
topk_idx_que = np.load('topk_idx/topk_idx_que_PC_avg_IVFPQ_pca.npy')
umls = pd.read_csv('UMLS_REL+RELA/UMLS_REL_posDEF.csv')
test = pd.read_csv('../SOURCE/PMC-VQA/test_clean.csv')[['Figure_path', 'Question', 'Answer']]

In [3]:
umls.iloc[0]

CUI1    Synthetic phospholipid used in liposomes and l...
REL                                     allowed qualifier
CUI2    Used with drugs for dosage forms, routes of ad...
Name: 0, dtype: object

In [3]:
concat_tri = umls.apply(lambda row: ' '.join(row), axis=1)

In [7]:
test['top1_img'] = concat_tri[topk_idx_img[:, 0]].reset_index(drop=True)
test['top2_img'] = concat_tri[topk_idx_img[:, 1]].reset_index(drop=True)
test['top3_img'] = concat_tri[topk_idx_img[:, 2]].reset_index(drop=True)
test['top4_img'] = concat_tri[topk_idx_img[:, 3]].reset_index(drop=True)
test['top5_img'] = concat_tri[topk_idx_img[:, 4]].reset_index(drop=True)
test['top1_que'] = concat_tri[topk_idx_que[:, 0]].reset_index(drop=True)
test['top2_que'] = concat_tri[topk_idx_que[:, 1]].reset_index(drop=True)
test['top3_que'] = concat_tri[topk_idx_que[:, 2]].reset_index(drop=True)
test['top4_que'] = concat_tri[topk_idx_que[:, 3]].reset_index(drop=True)
test['top5_que'] = concat_tri[topk_idx_que[:, 4]].reset_index(drop=True)
test

,Figure_path,Question,Answer,top1_img,top2_img,top3_img,top4_img,top5_img,top1_que,top2_que,top3_que,top4_que,top5_que
0,PMC8415802_FIG1.jpg,What is the name of the medical imaging techn...,Magnetic resonance imaging,A mixture of two T-lymphocyte preparations exp...,An emulsion containing the tartrate salt of th...,A recombinant immunotoxin consisting of the Fv...,An emulsion containing the tartrate salt of th...,A preparation of autologous T-lymphocytes that...,A surgical technique to correct REFRACTIVE ERR...,Surgical techniques on the CORNEA employing LA...,"Preparation of TOOTH surfaces, and of material...",The making of a continuous circular tear in th...,The removal of a cataractous CRYSTALLINE LENS ...
1,PMC8415802_FIG1.jpg,What is the appearance of the hyperintense fo...,Hypointense,A mixture of two T-lymphocyte preparations exp...,An emulsion containing the tartrate salt of th...,A recombinant immunotoxin consisting of the Fv...,An emulsion containing the tartrate salt of th...,A preparation of autologous T-lymphocytes that...,"Used with organs, animals, and higher plants a...","Used with organs, animals, and higher plants a...","Used with organs, animals, and higher plants a...","Used with organs, animals, and higher plants a...","Used with organs, animals, and higher plants a..."
2,PMC8415874_f5.jpg,What color did the soft tissue appear as in th...,Green,Surgical techniques on the CORNEA employing LA...,The progressive compaction of dispersed interp...,The removal of DNA LESIONS and/or restoration ...,Practices involved in preventing the transmiss...,The removal of DNA LESIONS and/or restoration ...,"a thin layer of tissue that covers organs, gla...","a thin layer of tissue that covers organs, gla...","a thin layer of tissue that covers organs, gla...","a thin layer of tissue that covers organs, gla...","a thin layer of tissue that covers organs, gla..."
3,PMC8415874_f6.jpg,What color represents the harder area in the ...,Blue,A quantitative microscopic finding indicating ...,A quantitative microscopic finding indicating ...,A semi-quantitative microscopic finding indica...,A semi-quantitative microscopic finding indica...,A semi-quantitative microscopic finding indica...,Cortical malformations secondary to abnormal n...,Congenital structural abnormalities of the DIG...,"The inner, i.e. lumen-facing, lipid bilayer of...",The lipid bilayer surrounding a dense core gra...,The lipid bilayer surrounding any of the compa...
4,PMC8415874_f7.jpg,What is the result of strain elastography in ...,Focal harder (blue) area,A laboratory test result that indicates the pr...,A laboratory test result indicating an abnorma...,A semi-quantitative microscopic finding indica...,A semi-quantitative microscopic finding indica...,A semi-quantitative microscopic finding indica...,antibodies directed against antigenic determin...,A syndrome characterized by the presence of rh...,A strain of PRIMATE T-LYMPHOTROPIC VIRUS 1 iso...,A subtype of molybdenum cofactor deficiency ca...,antibodies directed against antigenic determin...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,PMC8161276_toxins-13-00365-f005.jpg,What is depicted in figure (b)?,Location of the sonar probe,"Used with chemicals, biological, and non-biolo...","Used with chemicals, biological, and non-biolo...","Used with chemicals, biological, and non-biolo...","Used with chemicals, biological, and non-biolo...","Used with chemicals, biological, and non-biolo...",Physical location of ETS2_Gene gene has physic...,Human EXTL3 wild-type allele is located within...,Human EXT2 wild-type allele is located within ...,Physical location of EEF1A2_Gene gene has phys...,Physical location of MAFG_Gene gene has physic...
1996,PMC8161291_cancers-13-02490-f006.jpg,What does the inset of the representative flu...,Clusters of mitochondria colocalized with SQST...,"Administration of a liquid, drop by drop, into...",Radioimmunoassay of proteins using antibody co...,"<p>Irrigation, intragastric</p> has parent rel...",<p>Video media type.</p> has child relationshi...,<p>Topical</p> has parent relationship in a me...,A surgical procedure to correct MYOPIA by CORN...,The process of protecting various samples of b...,The act of cleansing the hands with water or o...,"appliance which is used for the correction, gu...",The most common type of neurofibromatosis. It ...
1997,PMC8161371_diagnostics-11-00906-f004.jpg,Which imaging technique was used to obtain th...,MRI,"nuclear, DNA binding protein; regulates transc...","angiotensin I, an inactive decapeptide, is cle...","An orally bioavailable, selective, arginine va...",A mitochondrial cytochrome P450 enzyme that ca...,A mixture of the mesylates (methane sulfonates...,A broad-specificity HLA-DR antigen that is ass...,An HLA-DR antigen associated with HLA-DRB1 CHA...,An HLA-DR antigen which is associated with HLA...,A broad-specificity HLA-DR antigen that is ass...,A HLA-DR antigen that is associated with HLA-D...
1998,PMC8161371_diagnostics-11-00906-f006.jpg,What color outlines the left multifidus muscl...,Purple,Soluble tumor necrosis factor receptor superfa...,"Protein S100-A1 (94 aa, ~11 kDa) is encoded by...","P2Y purinoceptor 2 (377 aa, ~42 kDa) is encode...","Protein S100-P (95 aa, ~10 kDa) is encoded by ...","Integral membrane protein GPR180 (440 aa, ~49 ...",A taxonomic family of lactic acid bacterium in...,"A genus of acid-fast Gram-positive, aerobic an...",Brachyspira pilosicoli mapped from A genus of ...,Yeast-like ascomycetous fungi of the family Sa...,"A family of gram-negative, aerobic bacteria th..."
1999,PMC8161439_clinpract-11-00046-f001.jpg,What is the location of the mass shown in the...,Above the superior rectus muscle,"Stage IIA includes: (T3, N0, M0); (T2, N1, M0)...","Stage IIIa includes: T1-3, N1, M0. T1: Tumor i...","Stage IIIA includes: (T2, N3a, M0); (T3, N2, M...","Stage III includes: IIIA: (T1, N2, M0); (T2, N...",This gene is involved in the epidermal growth ...,Computed tomography of the abdomen with the us...,Removal of tissue from the esophagus for micro...,Tests for central hearing disorders based on t...,The determination of the amount of deoxypyridi...,Characteristic or indicative of a condition. h...

In [11]:
import json
# Initialize an empty list to store JSON objects
json_data = []

# Iterate over each row in the DataFrame
for index, row in test.iterrows():
    # Create the JSON object
    json_obj = {
        "id": row['Figure_path'].split('.')[0],  # Extracting the image name from the path
        "image": row['Figure_path'],
        "conversations": [
            {
                "from": "human",
                "value": "The retrieved background Knowledge is given as follows: 1." + row['top1_que'].strip() + " 2." + row['top2_que'].strip() + " 3." + row['top1_img'].strip() + " 4." + row['top2_img'].strip() + " The question is: "+ row['Question'].strip()
            },
            {
                "from": "gpt",
                "value": row['Answer'].strip()
            }
        ]
    }
    # Append the JSON object to the list
    json_data.append(json_obj)

# Write the list of JSON objects to a JSON file
with open('llava_data/test_clean_top2.json', 'w') as f:
    json.dump(json_data, f, indent=2)

In [2]:
import pandas as pd

rel = pd.read_csv('UMLS_REL+RELA/UMLS_REL_hasDEF.csv')
defi = pd.read_csv('UMLS_DEF.csv').dropna()
defi

,cui,name,definition
0,C0000039,"DPPC, Phosphatidylcholine, Dipalmitoyl, Dipalm...",Synthetic phospholipid used in liposomes and l...
1,C0000052,"1,4 alpha Glucan Branching Enzyme, Amylo-(1,4-...","In glycogen or amylopectin synthesis, the enzy..."
2,C0000084,"3-Amino-1,1,3-propanetricarboxylic Acid, gamma...","Found in various tissues, particularly in four..."
3,C0000096,"1H-Purine-2,6-dione, 3,7-dihydro-1-methyl-3-(2...",A potent cyclic nucleotide phosphodiesterase i...
4,C0000097,"methylphenyltetrahydropyridine, N-Methyl-4-phe...",A dopaminergic neurotoxic compound which produ...
...,...,...,...
244906,C5847541,"Intervertebral somatic dysfunction type 1, Typ...",A group dysfunction of the thoracic and lumbar...
244907,C5847542,"Type II Intervertebral somatic dysfunction, In...",A single segmental dysfunction of the thoracic...
244908,C5847614,"Diabetes mellitus type 1 stage 1, Diabetes mel...",Represents individuals who have developed two ...
244909,C5847615,"Diabetes mellitus type 1 stage 2, Diabetes mel...",Includes individuals with two or more islet au...
244910,C5847622,"Diabetes mellitus type 1 stage 3, Diabetes mel...",Represents manifestations of the typical clini...

In [16]:
rel[rel['CUI2']=='C0001629']

             CUI1                                REL      CUI2
3094     C0000726                                CHD  C0022646
7488     C0000769                                 QB  C0022646
14165    C0001126                                PAR  C0022646
14180    C0001126                    finding_site_of  C0022646
33383    C0001625  is_location_of_anatomic_structure  C0022646
...           ...                                ...       ...
4196603  C5786796     is_associated_anatomic_site_of  C0022646
4196616  C5786797     is_associated_anatomic_site_of  C0022646
4196629  C5786798     is_associated_anatomic_site_of  C0022646
4196664  C5786800     is_associated_anatomic_site_of  C0022646
4196691  C5786803     is_associated_anatomic_site_of  C0022646

[1827 rows x 3 columns]

In [20]:
defi[defi['cui']=='C0022646']

,cui,name,definition
8708,C0022646,"Kidney structure (body structure), Kidney stru...",Body organ that filters blood for the secretio...

In [22]:
import pickle
with open('UMLS_NAME', 'rb') as fp:
    name_dict = pickle.load(fp)

In [24]:
name_dict['C0000039']

{'def': 'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS.',
 'name': ['Dipalmitoyllecithin',
  '1,2-dipalmitoylphosphatidylcholine',
  'Dipalmitoylphosphatidylcholine (substance)',
  '1,2-Dipalmitoylphosphatidylcholine',
  'Phosphatidylcholine, Dipalmitoyl',
  'Dipalmitoyl Phosphatidylcholine',
  '3,5,9-Trioxa-4-phosphapentacosan-1-aminium, 4-hydroxy-N,N,N-trimethyl-10-oxo-7-((1-oxohexadecyl)oxy)-, inner salt, 4-oxide',
  '1,2-Dihexadecyl-sn-Glycerophosphocholine',
  '1,2 Dihexadecyl sn Glycerophosphocholine',
  '1,2-Dipalmitoyl-Glycerophosphocholine',
  '1,2 Dipalmitoylphosphatidylcholine',
  'DIPALMITOYLPHOSPHATIDYLCHOLINE 0102',
  'DPPC',
  'Dipalmitoylglycerophosphocholine',
  'Dipalmitoylphosphatidylcholine',
  '1,2 Dipalmitoyl Glycerophosphocholine']}

In [1]:
import pandas as pd
doc_df = pd.read_csv('UMLS_DOC.csv').dropna()
doc_df['EXPL'] = doc_df['EXPL'].str.replace('_', ' ')
doc_df['EXPL'] = doc_df['EXPL'].str.lower()

In [2]:
umls_doc = {}
for i, row in doc_df.iterrows():
    umls_doc[row['VALUE']] = row['EXPL']

import pickle
with open('UMLS_REL', 'wb') as fp:
    pickle.dump(umls_doc, fp)

In [6]:
with open('UMLS_REL', 'rb') as fp:
    rel_dict = pickle.load(fp)
for k, v in rel_dict.items():
    print(k)

abnormal_cell_affected_by_chemical_or_drug
abnormality_associated_with_allele
absorbability_of
access_device_used_by
access_instrument_of
access_of
acted_on_by_process
active_ingredient_of
active_metabolites_of
active_moiety_of
activity_of_allele
adheres_to
adjacent_to
adjustment_of
afferent_to
after
alias_of
allele_absent_from_wild-type_chromosomal_location
allele_has_abnormality
allele_has_activity
allele_in_chromosomal_location
allele_plays_altered_role_in_process
allele_plays_role_in_metabolism_of_chemical_or_drug
allelic_variant_of
alternative_of
analyzed_by
analyzes
anatomic_structure_has_location
anatomic_structure_is_physical_part_of
anatomical_entity_observed_in
anatomy_originated_from_biological_process
answer_to_is_sterile
answer_to
anterior_to
anteroinferior_to
anterolateral_to
anteromedial_to
anterosuperior_to
approach_of
archetype_of
arterial_supply_of
articulates_with
associated_disease
associated_etiologic_finding_of
associated_finding_of
associated_function_of
associated_genetic_condition
associated_morphology_of
associated_procedure_of
associated_with_malfunction_of_gene_product
associated_with
attaches_to
away_from
basic_dose_form_of
basis_of_strength_substance_of
before
biological_process_has_associated_location
biological_process_has_initiator_chemical_or_drug
biological_process_has_initiator_process
biological_process_has_result_anatomy
biological_process_has_result_biological_process
biological_process_has_result_chemical_or_drug
biological_process_involves_chemical_or_drug
biological_process_involves_gene_product
biological_process_is_part_of_process
biological_process_results_from_biological_process
biomarker_type_includes_gene_product
biomarker_type_includes_gene
boss_of
bounded_by
bounds
branch_of
causative_agent_of
cause_of
cell_type_is_associated_with_eo_disease
cell_type_or_tissue_affected_by_chemical_or_drug
challenge_of
characterized_by
characterizes
chemical_or_drug_affects_abnormal_cell
chemical_or_drug_affects_cell_type_or_tissue
chemical_or_drug_affects_gene_product
chemical_or_drug_has_mechanism_of_action
chemical_or_drug_has_physiologic_effect
chemical_or_drug_initiates_biological_process
chemical_or_drug_is_metabolized_by_enzyme
chemical_or_drug_is_product_of_biological_process
chemical_or_drug_metabolism_is_associated_with_allele
chemical_or_drug_plays_role_in_biological_process
chemotherapy_regimen_has_component
chromosomal_location_of_allele
chromosomal_location_of_wild-type_gene
chromosome_involved_in_cytogenetic_abnormality
chromosome_mapped_to_disease
class_code_classified_by
class_of
classified_as
classifies_class_code
classifies
clinical_course_of
clinically_similar
coating_material_of
common_name_of
completely_excised_anatomy_has_procedure
completely_excised_anatomy_may_have_procedure
complex_has_physical_part
component_of
compositional_material_of
concentration_strength_denominator_unit_of
concentration_strength_denominator_value_of
concentration_strength_numerator_unit_of
concentration_strength_numerator_value_of
concept_in_subset
conceptual_part_of
connected_to
connection_type_of
consider_from
consider
consists_of
constitutes
constitutional_part_of
contained_in
contains
context_binding_of
continuation_branch_of
continuous_distally_with
continuous_proximally_with
continuous_with
contraindicated_class_of
contraindicated_mechanism_of_action_of
contraindicated_physiologic_effect_of
contraindicated_with_disease
corresponds_to
count_of_active_ingredient_of
count_of_base_of_active_ingredient_of
count_of
course_of
ctcae_5_parent_of
cytogenetic_abnormality_involves_chromosome
data_element_of
default_inpatient_classification_of
default_outpatient_classification_of
definitional_manifestation_of
degree_of
dependent_of
derives_from
derives
development_type_of
developmental_stage_of
develops_from
develops_into
device_characteristic_of
device_intended_site_of
device_used_by
diagnosed_by
diagnoses
direct_cell_shape_of
direct_device_of
direct_left_of
direct_morphology_of
direct_procedure_site_of
direct_right_of
direct_site_of
direct_substance_of
disease_excludes_abnormal_cell
disease_excludes_cytogenetic_abnormality
disease_excludes_finding
disease_excludes_metastatic_anatomic_site
disease_excludes_molecular_abnormality
disease_excludes_normal_cell_origin
disease_excludes_normal_tissue_origin
disease_excludes_primary_anatomic_site
disease_has_abnormal_cell
disease_has_accepted_treatment_with_regimen
disease_has_associated_anatomic_site
disease_has_associated_disease
disease_has_associated_gene
disease_has_cytogenetic_abnormality
disease_has_finding
disease_has_metastatic_anatomic_site
disease_has_molecular_abnormality
disease_has_normal_cell_origin
disease_has_normal_tissue_origin
disease_has_primary_anatomic_site
disease_is_grade
disease_is_marked_by_gene
disease_is_stage
disease_mapped_to_chromosome
disease_mapped_to_gene
disease_may_have_abnormal_cell
disease_may_have_associated_disease
disease_may_have_cytogenetic_abnormality
disease_may_have_finding
disease_may_have_molecular_abnormality
disease_may_have_normal_cell_origin
disease_may_have_normal_tissue_origin
disposition_of
distal_to
divisor_of
dose_form_administration_method_of
dose_form_intended_site_of
dose_form_of
dose_form_release_characteristic_of
dose_form_transformation_of
doseformgroup_of
drains_into
due_to
during
effect_may_be_inhibited_by
efferent_to
endogenous_product_related_to
ends_during
energy_used_by
entire_anatomy_structure_of
entry_term_of
entry_version_of
enzyme_metabolizes_chemical_or_drug
eo_anatomy_is_associated_with_eo_disease
eo_disease_has_associated_cell_type
eo_disease_has_associated_eo_anatomy
eo_disease_has_property_or_attribute
eo_disease_maps_to_human_disease
episodicity_of
evaluation_of
excised_anatomy_has_procedure
excised_anatomy_may_have_procedure
exhibited_by
exhibits
expanded_form_of
extended_to_by_process
extent_of
external_to
filling_of
finding_context_of
finding_informer_of
finding_method_of
finding_site_of
focus_of
form_of
formed_by
forms
full_grown_phenotype_of
fuses_with
fusion_of
gene_associated_with_disease
gene_encodes_gene_product
gene_found_in_organism
gene_has_abnormality
gene_has_physical_location
gene_in_chromosomal_location
gene_involved_in_molecular_abnormality
gene_involved_in_pathogenesis_of_disease
gene_is_biomarker_of
gene_is_biomarker_type
gene_is_element_in_pathway
gene_mapped_to_disease
gene_mutant_encodes_gene_product_sequence_variation
gene_plays_role_in_process
gene_product_affected_by_chemical_or_drug
gene_product_encoded_by_gene
gene_product_expressed_in_tissue
gene_product_has_abnormality
gene_product_has_associated_anatomy
gene_product_has_biochemical_function
gene_product_has_chemical_classification
gene_product_has_gene_product_variant
gene_product_has_organism_source
gene_product_has_structural_domain_or_motif
gene_product_is_biomarker_of
gene_product_is_biomarker_type
gene_product_is_element_in_pathway
gene_product_is_physical_part_of
gene_product_malfunction_associated_with_disease
gene_product_plays_role_in_biological_process
gene_product_sequence_variation_encoded_by_gene_mutant
gene_product_variant_of_gene_product
genetic_biomarker_related_to
germ_origin_of
happens_during
has_absorbability
has_acc-aha_sars2_authorized_value
has_access_instrument
has_access
has_action_guidance
has_active_ingredient
has_active_metabolites
has_active_moiety
has_adherent
has_adjustment
has_aggregation_view
has_alias
has_allelic_variant
has_alternative
has_answer
has_approach_guidance
has_approach
has_archetype
has_arterial_supply
has_associated_etiologic_finding
has_associated_finding
has_associated_function
has_associated_morphology
has_associated_procedure
has_basic_dose_form
has_basis_of_strength_substance
has_boss
has_branch
has_causative_agent
has_challenge
has_class
has_clinical_course
has_coating_material
has_common_name
has_communication_with_wound
has_component
has_compositional_material
has_concentration_strength_denominator_unit
has_concentration_strength_denominator_value
has_concentration_strength_numerator_unit
has_concentration_strength_numerator_value
has_conceptual_part
has_connection_type
has_constitutional_part
has_context_binding
has_continuation_branch
has_contraindicated_class
has_contraindicated_drug
has_contraindicated_mechanism_of_action
has_contraindicated_physiologic_effect
has_count_of_active_ingredient
has_count_of_base_of_active_ingredient
has_count
has_course
has_ctcae_5_parent
has_ctdc_value
has_data_element
has_default_inpatient_classification
has_default_outpatient_classification
has_definitional_manifestation
has_degree
has_dependent
has_development_type
has_developmental_stage
has_device_characteristic
has_device_intended_site
has_dipg_dmg_authorized_value
has_direct_cell_shape
has_direct_device
has_direct_morphology
has_direct_procedure_site
has_direct_site
has_direct_substance
has_disposition
has_divisor
has_dose_form_administration_method
has_dose_form_intended_site
has_dose_form_release_characteristic
has_dose_form_transformation
has_dose_form
has_doseformgroup
has_entire_anatomy_structure
has_entry_term
has_entry_version
has_episodicity
has_evaluation
has_exam
has_expanded_form
has_extent
has_filling
has_finding_context
has_finding_informer
has_finding_method
has_finding_site
has_focus
has_form
has_free_acid_or_base_form
has_full_grown_phenotype
has_fusion
has_gdc_value
has_gene_product_element
has_germ_origin
has_given_pharmaceutical_substance
has_icdc_value
has_imaged_location
has_imaging_focus
has_inactive_ingredient
has_inc_parent
has_indirect_device
has_indirect_morphology
has_indirect_procedure_site
has_ingredient_characteristic
has_ingredient_qualitative_strength
has_ingredients
has_ingredient
has_inherent_3d_shape
has_inherent_attribute
has_inherent_location
has_inheritance_type
has_insertion
has_instrumentation
has_intent
has_interpretation
has_lab_number
has_lateral_anatomic_location
has_lateral_location_presence
has_laterality
has_location
has_loinc_number
has_lymphatic_drainage
has_maneuver_type
has_manifestation
has_mapping_qualifier
has_measured_component
has_measurement_method
has_mechanism_of_action
has_member
has_method
has_modality_subtype
has_modality_type
has_modification
has_multi_level_category
has_nerve_supply
has_object_guidance
has_observed_anatomical_entity
has_occurrence
has_onset
has_ooro_pc_value
has_origin
has_owning_affiliate
has_owning_section
has_owning_subsection
has_parent_group
has_parent
has_part_anatomy_structure
has_part
has_pathological_process
has_pcdc_all_authorized_value
has_pcdc_aml_authorized_value
has_pcdc_data_type
has_pcdc_ews_authorized_value
has_pcdc_gct_authorized_value
has_pcdc_hl_authorized_value
has_pcdc_os_authorized_value
has_permuted_term
has_pharmaceutical_administration_method
has_pharmaceutical_basic_dose_form
has_pharmaceutical_intended_site
has_pharmaceutical_release_characteristics
has_pharmaceutical_route
has_pharmaceutical_state_of_matter
has_pharmaceutical_transformation
has_pharmacokinetics
has_phenotype
has_physical_part_of_anatomic_structure
has_physiologic_effect
has_precise_active_ingredient
has_precise_ingredient
has_precondition
has_presence_guidance
has_presentation_strength_denominator_unit
has_presentation_strength_denominator_value
has_presentation_strength_numerator_unit
has_presentation_strength_numerator_value
has_prev_name
has_prev_symbol
has_primary_segmental_supply
has_print_name
has_priority
has_procedure_context
has_procedure_device
has_procedure_morphology
has_procedure_site
has_process_duration
has_process_output
has_product_characteristic
has_product_monograph_title
has_projection
has_property_type
has_property
has_quantified_form
has_realization
has_recipient_category
has_regional_part
has_related_developmental_entity
has_result
has_revision_status
has_route_of_administration
has_salt_form
has_scale_type
has_scale
has_secondary_segmental_supply
has_segmental_composition
has_segmental_supply
has_seronet_authorized_value
has_severity
has_single_level_category
has_sort_version
has_specimen_procedure
has_specimen_source_identity
has_specimen_source_morphology
has_specimen_source_topography
has_specimen_substance
has_specimen
has_stage
has_state_of_matter
has_structural_class
has_subject_of_information
has_subject_relationship_context
has_subject
has_suffix
has_supersystem
has_supported_concept_property
has_supported_concept_relationship
has_surface_characteristic
has_surface_texture
has_surgical_approach
has_system
has_target_population
has_target
has_technique
has_temporal_context
has_therapeutic_class
has_time_aspect
has_time_modifier
has_timing_of
has_tradename
has_translation
has_tributary
has_unit_of_presentation
has_units
has_venous_drainage
has_version
has_view_type
homonym_for
homonym_of
human_disease_maps_to_eo_disease
icdc_value_of
imaged_anatomy_has_procedure
inactive_ingredient_of
inc_parent_of
included_in
includes
indirect_device_of
indirect_morphology_of
indirect_procedure_site_of
induced_by
induces
inferior_to
inferolateral_to
inferomedial_to
ingredient_characteristic_of
ingredient_of
ingredient_qualitative_strength_of
ingredients_of
inherent_3d_shape_of
inherent_location_of
inheres_in
inheritance_type_of
insertion_of
instrumentation_of
intent_of
internal_to
interpretation_of
interprets
inverse_during
inverse_ends_during
inverse_happens_during
inverse_isa
inverse_relative_to
inverse_was_a
is_abnormal_cell_of_disease
is_abnormality_of_gene_product
is_abnormality_of_gene
is_acc-aha_sars2_authorized_value_for_variable
is_action_guidance_for
is_aggregation_view_of
is_approach_guidance_for
is_associated_anatomic_site_of
is_associated_anatomy_of_gene_product
is_associated_disease_of
is_biochemical_function_of_gene_product
is_chemical_classification_of_gene_product
is_chromosomal_location_of_gene
is_component_of_chemotherapy_regimen
is_ctdc_value_of
is_cytogenetic_abnormality_of_disease
is_dipg_dmg_authorized_value_for_variable
is_exam_for
is_finding_of_disease
is_given_pharmaceutical_substance_for
is_grade_of_disease
is_imaged_location_for
is_imaging_focus_of
is_interpreted_by
is_lateral_anatomic_location_of
is_location_of_anatomic_structure
is_location_of_biological_process
is_maneuver_type_for
is_marked_by_gene_product
is_mechanism_of_action_of_chemical_or_drug
is_metastatic_anatomic_site_of_disease
is_modality_subtype_for
is_modality_type_for
is_modification_of
is_molecular_abnormality_of_disease
is_normal_cell_origin_of_disease
is_normal_tissue_origin_of_disease
is_not_abnormal_cell_of_disease
is_not_cytogenetic_abnormality_of_disease
is_not_finding_of_disease
is_not_metastatic_anatomic_site_of_disease
is_not_molecular_abnormality_of_disease
is_not_normal_cell_origin_of_disease
is_not_normal_tissue_origin_of_disease
is_not_primary_anatomic_site_of_disease
is_object_guidance_for
is_ooro_pc_value_of
is_organism_source_of_gene_product
is_paired_with_value_set
is_pcdc_all_authorized_value_for_variable
is_pcdc_aml_authorized_value_for_variable
is_pcdc_ews_authorized_value_for_variable
is_pcdc_gct_authorized_value_for_variable
is_pcdc_hl_authorized_value_for_variable
is_pcdc_os_authorized_value_for_variable
is_pharmaceutical_route_for
is_physical_location_of_gene
is_physiologic_effect_of_chemical_or_drug
is_presence_guidance_for
is_presence_of_lateral_location
is_primary_anatomic_site_of_disease
is_property_or_attribute_of_eo_disease
is_qualified_by
is_related_to_endogenous_product
is_seronet_authorized_value_for_variable
is_stage_of_disease
is_sterile
is_structural_domain_or_motif_of_gene_product
is_subject_of
is_target
is_timing_for
is_value_for_gdc_property
is_view_type_for
isa
kind_is_domain_of
kind_is_range_of
lab_number_of
larger_than
lateral_to
laterality_of
left_lateral_to
left_medial_to
location_of
loinc_number_of
lymphatic_drainage_of
manifestation_of
manufactured_by
manufactures
mapped_from
mapped_to
mapping_qualifier_of
matures_from
matures_into
may_be_abnormal_cell_of_disease
may_be_associated_disease_of_disease
may_be_cytogenetic_abnormality_of_disease
may_be_diagnosed_by
may_be_finding_of_disease
may_be_molecular_abnormality_of_disease
may_be_normal_cell_origin_of_disease
may_be_normal_tissue_origin_of_disease
may_be_prevented_by
may_be_qualified_by
may_be_treated_by
may_diagnose
may_inhibit_effect_of
may_prevent
may_qualify
may_treat
measured_by
measured_component_of
measurement_method_of
measures
mechanism_of_action_of
medial_to
member_of
merges_with
metabolic_site_of
method_of
molecular_abnormality_involves_gene
moved_from
moved_to
mth_expanded_form_of
mth_has_expanded_form
mth_has_plain_text_form
mth_has_xml_form
mth_plain_text_form_of
mth_xml_form_of
negatively_regulated_by
negatively_regulates
neoplasm_has_special_category
nerve_supply_of
occurs_after
occurs_before
occurs_in
onset_of
organism_has_gene
origin_of
owning_affiliate_of
owning_section_of
owning_subsection_of
parent_group_of
parent_of
part_anatomy_structure_of
part_of
part_referred_to_by
partially_equivalent_to
partially_excised_anatomy_has_procedure
partially_excised_anatomy_may_have_procedure
pathogenesis_of_disease_involves_gene
pathological_process_of
pathway_has_gene_element
pcdc_data_type_of
permuted_term_of
pharmaceutical_administration_method_of
pharmaceutical_basic_dose_form_of
pharmaceutical_intended_site_of
pharmaceutical_release_characteristics_of
pharmaceutical_state_of_matter_of
pharmaceutical_transformation_of
pharmacokinetics_of
phenotype_of
physiologic_effect_of
plays_role
positively_regulated_by
positively_regulates
possibly_equivalent_to
possibly_replaced_by
possibly_replaces
posterior_to
posteroinferior_to
posterolateral_to
posteromedial_to
posterosuperior_to
precise_active_ingredient_of
precise_ingredient_of
precondition_of
presentation_strength_denominator_unit_of
presentation_strength_denominator_value_of
presentation_strength_numerator_unit_of
presentation_strength_numerator_value_of
prev_name_of
prev_symbol_of
primary_segmental_supply_of
print_name_of
priority_of
procedure_context_of
procedure_device_of
procedure_has_completely_excised_anatomy
procedure_has_excised_anatomy
procedure_has_imaged_anatomy
procedure_has_partially_excised_anatomy
procedure_has_target_anatomy
procedure_may_have_completely_excised_anatomy
procedure_may_have_excised_anatomy
procedure_may_have_partially_excised_anatomy
procedure_morphology_of
procedure_site_of
process_acts_on
process_altered_by_allele
process_duration_of
process_extends_to
process_includes_biological_process
process_initiates_biological_process
process_involves_gene
process_output_of
product_characteristic_of
product_monograph_title_of
projects_from
projects_to
property_of
property_type_of
proximal_to
qualifier_applies_to
quantified_form_of
realization_of
receives_attachment_from
receives_drainage_from
receives_input_from
receives_projection
recipient_category_of
referred_to_by
refers_to
reformulated_to
reformulation_of
regimen_has_accepted_use_for_disease
regional_part_of
regulated_by
regulates
related_developmental_entity_of
related_object
related_part
related_to_genetic_biomarker
related_to
relative_to_part_of
relative_to
replaced_by
replaces
result_of
revision_status_of
right_lateral_to
right_medial_to
role_has_domain
role_has_parent
role_has_range
role_is_parent_of
role_played_by
route_of_administration_of
same_as
scale_of
scale_type_of
secondary_segmental_supply_of
see_from
see
segmental_composition_of
segmental_supply_of
sends_output_to
severity_of
site_of_metabolism
smaller_than
sort_version_of
special_category_includes_neoplasm
specimen_of
specimen_procedure_of
specimen_source_identity_of
specimen_source_morphology_of
specimen_source_topography_of
specimen_substance_of
stage_of
state_of_matter_of
structural_class_of
subject_of_information_of
subject_relationship_context_of
subset_includes_concept
substance_used_by
suffix_of
superior_to
superolateral_to
superomedial_to
supersystem_of
supported_concept_property_in
supported_concept_relationship_in
surface_characteristic_of
surface_texture_of
surgical_approach_of
surrounded_by
surrounds
system_of
target_anatomy_has_procedure

#### Inverted Index

In [3]:
import pandas as pd
from transformers import BertTokenizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
import collections
import re


# Function to remove stopwords
def remove_stopwords_and_punctuations(text):
    # Remove punctuations using regex
    text = re.sub(r'[^\w\s]', '', text)
    # Split the text into words and filter out stopwords
    words = text.split()
    words = [word for word in words if word.lower() not in ENGLISH_STOP_WORDS]
    return ' '.join(words)

# Function to create the inverted index
def create_inverted_index(token_id_lists):
    inverted_index = collections.defaultdict(set)

    for idx, token_ids in enumerate(token_id_lists):
        for token_id in token_ids:
            inverted_index[token_id].add(idx)

    return dict(inverted_index)

In [4]:
# load data
df = pd.read_csv('UMLS_REL+RELA/UMLS_REL_posDEF.csv')[:100]
# combine head, relation and entity
df['combined'] = df.apply(lambda row: ' '.join(row.values.astype(str)), axis=1)
# remove stopwords
df['cleaned'] = df['combined'].apply(remove_stopwords_and_punctuations)
# tokenize
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
df['token_ids'] = df['cleaned'].apply(lambda x: tokenizer.encode(x, add_special_tokens=True))
df

,CUI1,REL,CUI2,combined,cleaned,token_ids
0,Synthetic phospholipid used in liposomes and l...,allowed qualifier,"Used with drugs for dosage forms, routes of ad...",Synthetic phospholipid used in liposomes and l...,Synthetic phospholipid used liposomes lipid bi...,"[101, 12553, 6887, 2891, 8458, 10893, 23267, 2..."
1,Synthetic phospholipid used in liposomes and l...,allowed qualifier,"Used with drugs, chemicals, or biological agen...",Synthetic phospholipid used in liposomes and l...,Synthetic phospholipid used liposomes lipid bi...,"[101, 12553, 6887, 2891, 8458, 10893, 23267, 2..."
2,Synthetic phospholipid used in liposomes and l...,allowed qualifier,Used with drugs and chemicals for substances t...,Synthetic phospholipid used in liposomes and l...,Synthetic phospholipid used liposomes lipid bi...,"[101, 12553, 6887, 2891, 8458, 10893, 23267, 2..."
3,Synthetic phospholipid used in liposomes and l...,allowed qualifier,"Used with chemicals, drugs, and endogenous sub...",Synthetic phospholipid used in liposomes and l...,Synthetic phospholipid used liposomes lipid bi...,"[101, 12553, 6887, 2891, 8458, 10893, 23267, 2..."
4,Synthetic phospholipid used in liposomes and l...,allowed qualifier,Used for the anabolic formation of chemical su...,Synthetic phospholipid used in liposomes and l...,Synthetic phospholipid used liposomes lipid bi...,"[101, 12553, 6887, 2891, 8458, 10893, 23267, 2..."
...,...,...,...,...,...,...
95,"Found in various tissues, particularly in four...",allowed qualifier,Used with drugs and exogenously administered c...,"Found in various tissues, particularly in four...",various tissues particularly bloodclotting pro...,"[101, 2536, 14095, 3391, 2668, 20464, 21325, 3..."
96,"Found in various tissues, particularly in four...",allowed qualifier,Used with endogenous and exogenous substances ...,"Found in various tissues, particularly in four...",various tissues particularly bloodclotting pro...,"[101, 2536, 14095, 3391, 2668, 20464, 21325, 3..."
97,"Found in various tissues, particularly in four...",allowed qualifier,Used for the chemical preparation of molecules...,"Found in various tissues, particularly in four...",various tissues particularly bloodclotting pro...,"[101, 2536, 14095, 3391, 2668, 20464, 21325, 3..."
98,"Found in various tissues, particularly in four...",has parent relationship in a metathesaurus sou...,Derivatives of GLUTAMIC ACID. Included under t...,"Found in various tissues, particularly in four...",various tissues particularly bloodclotting pro...,"[101, 2536, 14095, 3391, 2668, 20464, 21325, 3..."
99,"Found in various tissues, particularly in four...",has parent relationship in a metathesaurus sou...,Organic compounds that are acyclic and contain...,"Found in various tissues, particularly in four...",various tissues particularly bloodclotting pro...,"[101, 2536, 14095, 3391, 2668, 20464, 21325, 3..."

In [7]:
token_id_lists = df['token_ids'].tolist()
row_wise_inverted_index = create_inverted_index(token_id_lists)
row_wise_inverted_index

{101: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 12553: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  65},
 6887: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  45,
  47,
  49,
  60,
  80,
  82,
  84,
  91,
  95},
 2891: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 8458: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 10893: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 23267: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 2109: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97},
 5423: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 19137: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 7834: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 3593: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 12170: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 24314: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 2015: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  37,
  38,
  43,
  45,
  46,
  50,
  51,
  56,
  58,
  59,
  62,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 2817: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 6897: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  35,
  36,
  44,
  52,
  56,
  65,
  69,
  71,
  79,
  87,
  90},
 24972: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 2350: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 13794: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 21908: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 14175: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 18908: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  36,
  71},
 11390: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33},
 3039: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97},
 10981: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97},
 5850: {0,
  1,
  2,
  3,
  12,
  15,
  16,
  17,
  19,
  20,
  23,
  26,
  34,
  35,
  36,
  45,
  48,
  49,
  50,
  52,
  53,
  57,
  60,
  68,
  69,
  70,
  71,
  80,
  83,
  84,
  85,
  87,
  88,
  91,
  92,
  95},
 9998: {0, 1, 13, 34, 35, 46, 68, 69, 81},
 4270: {0, 1, 13, 29, 34, 35, 46, 68, 69, 81},
 3596: {0, 34, 68, 98},
 5847: {0, 34, 68},
 3447: {0, 20, 34, 53, 68, 88},
 6075: {0, 34, 68},
 9367: {0, 34, 68},
 11712: {0, 34, 68},
 14667: {0, 15, 34, 48, 68, 83},
 3896: {0,
  1,
  3,
  16,
  20,
  26,
  34,
  35,
  36,
  49,
  53,
  57,
  60,
  68,
  69,
  71,
  84,
  88,
  92,
  95},
 5876: {0, 34, 68},
 102: {0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 12141: {1,
  2,
  3,
  9,
  11,
  12,
  15,
  16,
  17,
  20,
  22,
  23,
  24,
  35,
  36,
  42,
  44,
  45,
  48,
  49,
  50,
  53,
  56,
  57,
  58,
  69,
  70,
  71,
  77,
  79,
  80,
  83,
  84,
  85,
  88,
  90,
  91,
  92,
  93},
 6074: {1, 3, 19, 20, 23, 35, 36, 52, 53, 69, 71, 87, 88, 91},
 3970: {1, 35, 69},
 3558: {1, 19, 35, 52, 69, 87},
 7609: {1, 35, 69},
 3688: {1, 35, 69},
 3671: {1, 9, 14, 27, 35, 42, 47, 61, 69, 77, 82, 96},
 8192: {1, 35, 69},
 3832: {1, 35, 69},
 16474: {1, 24, 35, 58, 69, 93},
 17261: {1, 24, 35, 58, 69, 93},
 17678: {1, 19, 35, 52, 69, 87},
 29598: {1, 19, 35, 52, 69, 87},
 28804: {1, 35, 69},
 2019: {1, 35, 69},
 4355: {1, 35, 69},
 20086: {1, 35, 69},
 5682: {1, 24, 35, 58, 69, 93},
 15316: {1, 35, 69},
 12763: {1, 35, 69},
 11707: {1, 35, 69},
 8853: {1, 24, 35, 58, 69, 93},
 13978: {2,
  3,
  4,
  5,
  6,
  11,
  14,
  21,
  22,
  23,
  25,
  26,
  27,
  28,
  36,
  37,
  38,
  39,
  44,
  47,
  55,
  56,
  59,
  60,
  61,
  62,
  70,
  71,
  72,
  73,
  74,
  79,
  82,
  89,
  90,
  91,
  94,
  95,
  96,
  97},
 3745: {2, 70},
 6687: {2, 29, 33, 63, 65, 70, 98, 99},
 13922: {2, 63, 70},
 2714: {2,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  70},
 4816: {2, 70},
 3252: {2, 22, 33, 56, 70, 90, 98},
 11234: {2, 70},
 2804: {2, 70},
 20885: {2, 70},
 13353: {2, 70},
 10737: {2, 12, 28, 45, 62, 65, 70, 80, 97},
 3563: {2, 12, 25, 45, 59, 70, 80, 94},
 5072: {2,
  4,
  13,
  22,
  25,
  26,
  28,
  37,
  46,
  56,
  59,
  60,
  62,
  70,
  72,
  81,
  90,
  94,
  95,
  97},
 5825: {2, 17, 50, 70, 85, 98},
 2800: {2, 70},
 6413: {2, 70},
 2177: {2,
  31,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  70},
 6526: {2, 70},
 2203: {3, 9, 14, 23, 27, 30, 32, 36, 42, 47, 61, 71, 77, 82, 91, 96},
 23924: {3,
  9,
  13,
  14,
  23,
  26,
  27,
  30,
  32,
  36,
  42,
  46,
  47,
  60,
  61,
  71,
  77,
  81,
  82,
  91,
  95,
  96},
 3560: {3, 9, 13, 23, 27, 30, 32, 36, 42, 46, 61, 71, 77, 81, 91, 96},
 5769: {3, 23, 36, 71, 91},
 4675: {3, 36, 71},
 7337: {3, 13, 36, 46, 71, 81},
 9617: {4, 12, 37, 45, 72, 80},
 18647: {4, 12, 37, 45, 72, 80},
 4195: {4, 28, 37, 62, 72, 97},
 11767: {4,
  9,
  11,
  12,
  14,
  16,
  22,
  25,
  26,
  28,
  37,
  42,
  44,
  45,
  47,
  49,
  56,
  57,
  59,
  60,
  62,
  72,
  77,
  79,
  80,
  82,
  84,
  90,
  92,
  94,
  95,
  97},
 2542: {4, 16, 26, 28, 37, 49, 60, 62, 72, 84, 95, 97},
 4442: {4, 12, 14, 28, 37, 45, 47, 54, 62, 72, 80, 82, 97},
 4942: {4, 5, 12, 25, 28, 37, 38, 45, 59, 62, 72, 73, 80, 94, 97},
 16882: {4, 12, 14, 28, 37, 45, 47, 62, 72, 80, 82, 97},
 12884: {4, 12, 28, 37, 45, 62, 72, 80, 97},
 3739: {5, 6, 11, 21, 38, 39, 44, 55, 67, 73, 74, 79, 89},
 4106: {5, 6, 21, 22, 25, 38, 39, 55, 56, 59, 73, 74, 89, 90, 94},
 2668: {5,
  25,
  38,
  59,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 7749: {5, 6, 21, 38, 39, 55, 73, 74, 89},
 3431: {5, 6, 12, 21, 38, 39, 45, 55, 73, 74, 80, 89},
 4295: {5, 6, 19, 21, 30, 38, 39, 52, 55, 73, 74, 87, 89},
 2163: {5, 6, 9, 38, 39, 42, 73, 74, 77},
 23329: {5, 10, 18, 22, 25, 38, 43, 51, 56, 59, 73, 78, 86, 90, 94},
 14262: {5, 38, 73},
 7716: {5, 38, 73},
 2401: {5, 38, 73},
 26745: {5, 38, 73},
 6190: {5, 38, 66, 73},
 4974: {5, 12, 25, 38, 45, 59, 73, 80, 94},
 2075: {5, 25, 38, 59, 73, 94},
 11616: {5, 24, 38, 58, 73, 93},
 6779: {5, 38, 73},
 10047: {5, 11, 24, 38, 44, 58, 73, 79, 93},
 23041: {5, 11, 24, 38, 44, 58, 73, 79, 93},
 8292: {6, 25, 39, 59, 74, 94},
 2890: {6, 25, 39, 59, 74, 94},
 12618: {6, 25, 39, 59, 74, 94},
 13102: {6, 25, 39, 59, 74, 94},
 13290: {6, 25, 39, 59, 74, 94},
 8331: {6, 25, 39, 59, 74, 94},
 27691: {7, 40, 75},
 11778: {7, 40, 75},
 25835: {7, 40, 75},
 5579: {7, 40, 75},
 3001: {7, 40, 75},
 3171: {8, 41, 76},
 5919: {8, 9, 10, 24, 41, 42, 43, 58, 76, 77, 78, 93},
 3395: {8, 10, 41, 43, 76, 78},
 3361: {8, 41, 76},
 2968: {8, 41, 76},
 2950: {8,
  9,
  10,
  16,
  17,
  19,
  20,
  24,
  25,
  26,
  41,
  42,
  43,
  49,
  50,
  52,
  53,
  58,
  59,
  60,
  76,
  77,
  78,
  84,
  85,
  87,
  88,
  93,
  94,
  95},
 6274: {8, 41, 76},
 4346: {8, 41, 76},
 5029: {8, 41, 76},
 10595: {9, 26, 42, 60, 77, 95},
 2182: {9, 42, 77},
 25469: {9, 42, 77},
 14471: {9, 42, 77},
 7403: {9, 42, 77},
 3978: {9, 42, 77},
 4130: {9, 42, 77},
 12898: {9, 11, 24, 42, 44, 58, 77, 79, 93},
 12863: {9, 11, 24, 42, 44, 58, 77, 79, 93},
 16012: {9,
  12,
  13,
  14,
  26,
  27,
  28,
  42,
  45,
  46,
  47,
  60,
  61,
  62,
  77,
  80,
  81,
  82,
  95,
  96,
  97},
 15869: {9, 12, 14, 26, 42, 45, 47, 60, 77, 80, 82, 95},
 8382: {9, 42, 77},
 3747: {9, 42, 77},
 3430: {9, 18, 42, 51, 77, 86},
 3439: {10, 43, 78},
 4766: {10, 43, 78},
 3964: {10, 43, 78},
 2553: {10, 43, 78},
 15215: {10, 43, 78},
 10327: {11, 44, 79},
 18191: {11, 24, 44, 58, 79, 93},
 15289: {11, 24, 44, 58, 79, 93},
 15053: {11, 44, 79},
 6844: {11, 44, 79},
 2050: {11, 44, 79},
 16254: {11, 44, 79},
 18447: {11, 44, 79},
 7898: {11, 44, 79},
 11381: {11, 44, 79},
 5760: {11, 44, 79},
 18859: {11, 44, 79},
 10467: {11, 44, 79},
 8720: {11, 17, 25, 44, 50, 59, 79, 85, 94},
 6064: {11, 44, 65, 79},
 16478: {11, 44, 79},
 4725: {11, 44, 79},
 2164: {11,
  44,
  54,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 3226: {11, 44, 79},
 5461: {11, 44, 79},
 12477: {11, 22, 44, 56, 79, 90},
 28406: {11, 22, 44, 56, 79, 90},
 24355: {11, 16, 25, 44, 49, 59, 79, 84, 94},
 11595: {12, 14, 16, 22, 24, 45, 47, 49, 56, 57, 58, 80, 82, 84, 90, 92, 93},
 7870: {12, 24, 45, 58, 80, 93},
 4937: {12,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  80},
 7875: {12, 45, 80},
 23518: {12, 45, 80},
 12554: {12, 45, 80},
 3375: {12, 45, 80},
 16325: {12, 45, 80},
 3924: {12, 45, 80},
 6194: {12, 13, 16, 26, 45, 46, 49, 57, 60, 80, 81, 84, 92, 95},
 7584: {12, 45, 80},
 2235: {12, 45, 80},
 2312: {12, 33, 45, 80},
 6508: {12, 28, 45, 62, 80, 97},
 3372: {12, 28, 45, 62, 80, 97},
 24124: {12, 28, 45, 62, 80, 97},
 4372: {12, 45, 80},
 9096: {12, 45, 80},
 20570: {12, 45, 80},
 27292: {12, 23, 26, 45, 60, 80, 91, 95},
 22684: {12, 23, 26, 45, 60, 80, 91, 95},
 4939: {12, 45, 80},
 16530: {12, 45, 80},
 2224: {12, 19, 45, 52, 80, 87},
 8613: {12, 45, 80},
 10949: {13, 46, 81},
 20504: {13, 46, 81},
 4654: {13, 26, 27, 46, 60, 61, 81, 95, 96},
 4319: {13, 30, 32, 46, 81},
 16326: {13, 46, 81},
 6494: {13, 46, 81},
 3619: {13, 46, 81},
 14192: {13, 46, 81},
 3370: {13, 46, 81},
 4353: {13, 18, 46, 51, 81, 86},
 2713: {13, 46, 81},
 3665: {13, 46, 81},
 2039: {13, 46, 81},
 15166: {13, 46, 81},
 9614: {13, 46, 81},
 3853: {13, 14, 33, 46, 47, 81, 82},
 6698: {13, 46, 81},
 3446: {13, 46, 81},
 21453: {13, 46, 81},
 14095: {14,
  16,
  24,
  25,
  26,
  47,
  49,
  54,
  57,
  58,
  59,
  60,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 4895: {14, 47, 82},
 6610: {14, 47, 82},
 3363: {14, 47, 82},
 7934: {14, 47, 82},
 4800: {14, 47, 82},
 13453: {14, 26, 47, 60, 82, 95},
 2550: {14, 47, 82},
 7274: {14, 16, 47, 49, 82, 84},
 20282: {14, 16, 47, 49, 82, 84},
 8649: {14, 16, 33, 47, 49, 82, 84},
 2594: {14,
  16,
  47,
  49,
  54,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 2535: {14, 47, 82},
 3919: {15, 48, 83},
 4475: {15, 48, 83},
 2529: {15, 20, 48, 53, 83, 88},
 4111: {15, 20, 48, 53, 83, 88},
 16149: {15, 20, 48, 53, 83, 88},
 11325: {15, 48, 83},
 11888: {15, 48, 83},
 17128: {15, 48, 83},
 16928: {15, 48, 83},
 26094: {15, 48, 83},
 7561: {15, 48, 83},
 4483: {15, 20, 25, 48, 53, 59, 83, 88, 94},
 7524: {15, 20, 48, 53, 83, 88},
 10163: {16, 49, 84},
 6026: {16, 49, 84},
 2512: {16, 22, 49, 56, 84, 90},
 3258: {16, 49, 84},
 8249: {16, 49, 84},
 3466: {16, 49, 84},
 20868: {16, 49, 84},
 12173: {16, 49, 84},
 18963: {16, 49, 84},
 4128: {17, 18, 50, 51, 85, 86},
 5073: {17, 18, 50, 51, 85, 86},
 2565: {17, 50, 85},
 2458: {17, 50, 85},
 5604: {17, 50, 85},
 4646: {17, 50, 85},
 4781: {17, 50, 85},
 4748: {17, 50, 85},
 2063: {17, 50, 85},
 16211: {17, 50, 85},
 5666: {17, 50, 85},
 11701: {17, 50, 85},
 2836: {17, 50, 85},
 3737: {17, 50, 85},
 8962: {17, 50, 85},
 11916: {17, 50, 85},
 2740: {17, 18, 50, 51, 85, 86},
 3808: {17, 20, 50, 53, 85, 88},
 6088: {17, 18, 50, 51, 85, 86},
 23374: {17, 18, 50, 51, 85, 86},
 20155: {18, 25, 51, 59, 86, 94},
 11343: {18, 51, 86},
 3941: {18, 51, 86},
 2578: {18, 51, 86},
 2833: {18, 51, 86},
 4425: {18, 51, 86},
 2300: {18, 25, 51, 59, 86, 94},
 12929: {19, 52, 87},
 8528: {19, 52, 87},
 2483: {19, 52, 87},
 3949: {19, 30, 32, 52, 87},
 15651: {19, 52, 87},
 6388: {20, 53, 88},
 2913: {20, 24, 53, 58, 88, 93},
 5665: {20, 53, 88},
 5646: {20, 53, 88},
 7785: {20, 53, 88},
 9597: {20, 53, 88},
 10860: {20, 53, 88},
 2536: {20,
  53,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 13004: {20, 53, 88},
 3798: {20, 53, 88},
 2641: {20, 53, 88},
 2166: {20, 53, 88},
 2705: {20,
  53,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99},
 29313: {20, 53, 88},
 5582: {20, 53, 88},
 17996: {21, 25, 55, 59, 89, 94},
 26282: {22, 56, 90},
 9966: {22, 56, 90},
 5512: {22, 56, 90},
 23191: {22, 56, 90},
 5144: {22, 30, 32, 56, 90},
 4180: {22, 56, 90},
 8153: {22, 56, 90},
 21434: {22, 25, 56, 59, 90, 94},
 2303: {22, 25, 56, 59, 90, 94},
 20989: {22, 25, 30, 32, 56, 59, 90, 94},
 4264: {22, 25, 56, 59, 90, 94},
 9128: {22, 25, 56, 59, 90, 94},
 10752: {22,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  90},
 16730: {23, 91},
 10769: {23, 91},
 23807: {23, 91},
 4023: {23, 65, 91},
 16432: {23, 91},
 6483: {23, 91},
 2889: {23, 91},
 1052: {23, 91, 99},
 16048: {23, 91},
 12702: {24, 54, 58, 93},
 21759: {24, 54, 58, 93},
 7088: {24, 54, 58, 93},
 19230: {24, 54, 58, 93},
 4176: {24, 58, 93},
 4652: {24, 30, 32, 58, 93},
 3512: {24, 58, 93},
 9740: {24, 58, 93},
 2491: {24, 58, 93},
 7242: {24, 58, 93},
 4145: {24, 25, 58, 59, 93, 94},
 28873: {24, 58, 93},
 5292: {24, 58, 93},
 13876: {24, 58, 93},
 6132: {24, 58, 93},
 9415: {25, 59, 94},
 18804: {25, 29, 33, 59, 63, 65, 94, 98, 99},
 14956: {25, 59, 94},
 7616: {25, 59, 94},
 2250: {25, 59, 94},
 6839: {25, 59, 94},
 6370: {25, 59, 94},
 12033: {25, 59, 94},
 16134: {25, 59, 94},
 3463: {25, 59, 94},
 2640: {25, 59, 94},
 5844: {25, 59, 94},
 8564: {26, 60, 95},
 16264: {26, 60, 95},
 23586: {26, 60, 95},
 19389: {26, 57, 60, 92, 95},

In [10]:
row_wise_inverted_index[101]

set

In [11]:
df['cleaned'][0]

'Synthetic phospholipid used liposomes lipid bilayers study biological membranes major constituent PULMONARY SURFACTANTS allowed qualifier Used drugs dosage forms routes administration frequency duration administration quantity medication effects factors'

In [12]:
df['combined'][0]

'Synthetic phospholipid used in liposomes and lipid bilayers to study biological membranes. It is also a major constituent of PULMONARY SURFACTANTS. allowed qualifier Used with drugs for dosage forms, routes of administration, frequency and duration of administration, quantity of medication, and the effects of these factors.'

In [14]:
import pickle
with open('inverted_index', 'rb') as fp:
    rel_dict = pickle.load(fp)
rel_dict[11867]

{1540104,
 163856,
 229415,
 1376314,
 589893,
 1867868,
 1867869,
 1867870,
 1867871,
 1867872,
 1867873,
 1867874,
 99,
 1474693,
 229520,
 229521,
 3211430,
 3211431,
 3211432,
 2687171,
 2687172,
 2687173,
 2687174,
 2687175,
 2687176,
 3408114,
 1376499,
 1376500,
 1376501,
 1376502,
 3408119,
 3408120,
 3408121,
 3408122,
 3408115,
 3408116,
 3408118,
 3408123,
 3408124,
 3408128,
 3408129,
 3408130,
 3408131,
 3408132,
 3408133,
 3408125,
 3408126,
 3408127,
 3080458,
 1114402,
 3342645,
 1671503,
 65872,
 1671504,
 1671505,
 1671506,
 1671507,
 1671508,
 1671509,
 1671510,
 1671511,
 1671512,
 1671514,
 1671515,
 1671516,
 1671517,
 1671513,
 262494,
 1671518,
 1671519,
 983411,
 819583,
 2687450,
 3047904,
 983525,
 2261562,
 2261563,
 2261564,
 262745,
 3572345,
 4031114,
 3408542,
 3408543,
 3408544,
 3048105,
 1344171,
 1344172,
 1344173,
 1344174,
 1344175,
 1344176,
 1344177,
 1344178,
 1344179,
 1344180,
 1344181,
 1344182,
 1344183,
 1344184,
 1344185,
 1344186,
 1344187,
 1344188,
 1344189,
 1344190,
 1344191,
 1344192,
 1344193,
 1344194,
 1344195,
 1344196,
 1344197,
 1344198,
 1344199,
 1344200,
 1344201,
 1344202,
 1344203,
 3408621,
 3408622,
 3408623,
 3408625,
 3408626,
 1114869,
 1114875,
 3539709,
 3539713,
 3539718,
 2687782,
 3080998,
 2687785,
 590642,
 263026,
 131957,
 131958,
 2458542,
 4162492,
 4162493,
 4162494,
 4162495,
 4162496,
 4162497,
 4162498,
 4162499,
 4162500,
 2687952,
 3900370,
 1475548,
 4162607,
 4162608,
 4162609,
 2688053,
 1213497,
 2655323,
 4162706,
 4162707,
 4162708,
 4162802,
 4162803,
 4162804,
 4162805,
 4031734,
 4162807,
 4162806,
 4162820,
 3671317,
 2688287,
 4162869,
 1213772,
 3736931,
 1377663,
 1377664,
 1377665,
 1377666,
 1377667,
 1377668,
 1377669,
 1377670,
 1377671,
 1377672,
 1377673,
 1377674,
 1377675,
 1377676,
 1377677,
 1377678,
 1377679,
 1377680,
 1377681,
 1377682,
 1377683,
 1377684,
 1377685,
 1377686,
 1377687,
 1377688,
 1377689,
 1377690,
 1377691,
 1377692,
 1377693,
 1377694,
 1377695,
 1377696,
 1377697,
 1377698,
 1377699,
 1377700,
 1377701,
 1377702,
 1377703,
 1377704,
 1377705,
 1377706,
 1377707,
 1377708,
 1377709,
 1377710,
 1377711,
 1377712,
 1377713,
 1377714,
 1377715,
 1377716,
 1377717,
 1377718,
 1377719,
 1377720,
 1377721,
 1377722,
 1377723,
 1377724,
 4163005,
 4163006,
 4163007,
 4163008,
 4163009,
 4163010,
 1377725,
 1377726,
 1377727,
 1377728,
 1377729,
 1377730,
 1377731,
 3671496,
 4163017,
 4163018,
 4163019,
 3671497,
 3671498,
 3671499,
 3671500,
 3671501,
 4163025,
 4163026,
 4163027,
 4163021,
 4163022,
 4163023,
 4163024,
 3081687,
 4163028,
 4163032,
 4163033,
 4163034,
 1377759,
 1377760,
 1377761,
 1377762,
 2688481,
 1377764,
 2688502,
 2262536,
 2262537,
 2262538,
 2262539,
 2262540,
 2262541,
 2262542,
 2262543,
 2262544,
 2262545,
 2262546,
 2262547,
 2262548,
 2262549,
 2262550,
 2262551,
 296476,
 1279534,
 951872,
 67160,
 67162,
 3442287,
 3442288,
 3442289,
 3442290,
 231078,
 951995,
 2688737,
 1181446,
 1967889,
 395049,
 2688820,
 100149,
 1214307,
 1214308,
 984983,
 2394008,
 2688935,
 2688936,
 3573672,
 3901358,
 3901362,
 3737547,
 2394067,
 4032471,
 4032518,
 3868680,
 559121,
 4163612,
 4163613,
 526366,
 4163614,
 526368,
 4163618,
 4163619,
 4163620,
 4163621,
 4163622,
 4163623,
 2263095,
 2263096,
 3246140,
 2263107,
 2263108,
 2787400,
 2263137,
 3442790,
 2263144,
 2263148,
 231535,
 3442815,
 1181825,
 100496,
 716855,
 3541155,
 3541156,
 3541157,
 3541158,
 3541159,
 3541160,
 3541161,
 3541162,
 3541163,
 3541164,
 3541165,
 3541166,
 3541167,
 100539,
 821435,
 3016892,
 716863,
 4032737,
 100581,
 716872,
 35065,
 2984191,
 716877,
 4032795,
 716882,
 2656574,
 1149248,
 716890,
 3901809,
 35193,
 2656651,
 2263436,
 1542553,
 919986,
 919987,
 3115477,
 3115478,
 2066920,
 821761,
 2656799,
 1280556,
 3738205,
 2263646,
 3607152,
 3541652,
 85206,
 4033202,
 3115731,
 1133804,
 1182510,
 1182511,
 1543033,
 3902341,
 1739659,
 1706911,
 1739680,
 1706929,
 1739714,
 68596,
 1215496,
 330765,
 330766,
 330768,
 330772,
 1248302,
 1248303,
 3607601,
 3738688,
 330827,
 986208,
 101485,
 3771525,
 822411,
 822412,
 986279,
 3083494,
 2657532,
 1215744,
 101649,
 3902746,
 3902764,
 3902785,
 4099400,
 4099401,
 4099402,
 4099403,
 3902806,
 3902824,
 3902832,
 101791,
 2788840,
 953837,
 331260,
 4034092,
 265773,
 2264621,
 4034093,
 3542645,
 331392,
 331393,
 3542670,
 3542671,
 3542672,
 3542673,
 3542674,
 3542675,
 3542676,
 3542689,
 3542690,
 3542691,
 3542692,
 3542693,
 3542694,
 3542695,
 3542696,
 3542697,
 3542698,
 3542699,
 3542700,
 2756269,
 3542701,
 3542702,
 3542727,
 3542728,
 3542732,
 3542733,
 3542734,
 1543918,
 1543919,
 2789115,
 331520,
 4198159,
 3739408,
 4198160,
 4198161,
 4198162,
 3084137,
 593796,
 3280806,
 3608494,
 364476,
 364477,
 364478,
 364479,
 364480,
 364481,
 364482,
 364483,
 364484,
 364485,
 364486,
 364487,
 364488,
 364489,
 364490,
 364491,
 4132812,
 364492,
 364493,
 364494,
 364495,
 3018704,
 3018705,
 3018706,
 3018707,
 364496,
 364497,
 364498,
 364499,
 364500,
 364505,
 1347543,
 1347544,
 364504,
 364508,
 364509,
 364510,
 364511,
 364512,
 364513,
 3018723,
 3018724,
 3018725,
 3018726,
 3018727,
 3018728,
 3018729,
 3018730,
 3018731,
 3018732,
 3018733,
 3018734,
 3018735,
 4067313,
 4067314,
 4067315,
 3018736,
 4067317,
 3018737,
 3018738,
 3018739,
 3018740,
 3018741,
 3018742,
 3018743,
 3018744,
 3018745,
 3018746,
 3018747,
 3018748,
 3018749,
 3018750,
 3018751,
 3018752,
 3018753,
 3018754,
 3018755,
 3018756,
 3018757,
 3018758,
 3018759,
 3018760,
 3018761,
 3018762,
 3018763,
 3018764,
 3018765,
 3018766,
 3018767,
 3018768,
 3018769,
 3018770,
 3018771,
 3018772,
 3018773,
 3018774,
 3018775,
 3018776,
 3018777,
 3018778,
 3018779,
 3018780,
 3018781,
 3018782,
 3018783,
 3018784,
 3018785,
 3018786,
 3018787,
 3018788,
 3018789,
 3018790,
 3018791,
 3018792,
 3018793,
 3018794,
 790584,
 36944,
 954464,
 3772573,
 3281056,
 888993,
 2330789,
 3084463,
 4133040,
 3084468,
 3084469,
 1970366,
 954574,
 3281140,
 3281141,
 3281142,
 3281143,
 3281144,
 3281145,
 3281146,
 3281147,
 3281148,
 3281149,
 3281150,
 3281151,
 3281152,
 3281153,
 3281154,
 1839373,
 1839374,
 1839375,
 1839376,
 1839377,
 2789650,
 2789651,
 1839378,
 1839379,
 1839380,
 1839381,
 1839382,
 1839383,
 1839384,
 1839385,
 1839386,
 1839387,
 1839388,
 1839389,
 1839390,
 1839391,
 1839392,
 2068769,
 1839393,
 1839395,
 1839394,
 2068775,
 2953504,
 1839442,
 1839446,
 1184100,
 627051,
 3928169,
 3477908,
 790937,
 3281320,
 790956,
 397750,
 790970,
 790974,
 790979,
 987589,
 987590,
 790983,
 987591,
 987592,
 987593,
 987594,
 2331084,
 1741279,
 2331110,
 692712,
 791017,
 791022,
 1741309,
 397829,
 3183154,
 3183181,
 3773024,
 3773025,
 3773035,
 3740294,
 3740295,
 3296469,
 397974,
 3740310,
 4100761,
 3740323,
 823978,
 987820,
 889520,
 889526,
 3740372,
 1184469,
 3740373,
 3740407,
 2331401,
 2331402,
 2331404,
 2331426,
 2331427,
 2331439,
 3347261,
 2331470,
 2331471,
 2331473,
 3478355,
 2331479,
 2331480,
 2331481,
 2331482,
 2331496,
 2331500,
 1217390,
 1217391,
 1217392,
 1217393,
 1217394,
 1217395,
 1217396,
 1217397,
 1217398,
 1217399,
 1217400,
 1217401,
 1217402,
 1217403,
 1217404,
 1217405,
 1217406,
 1217407,
 1217408,
 1217409,
 1217410,
 1217411,
 1217412,
 1217413,
 1217414,
 1020807,
 1217415,
 1217416,
 1217417,
 1217418,
 1217419,
 1217420,
 1217422,
 1217423,
 1217424,
 1217425,
 1217426,
 1217427,
 1217421,
 1217429,
 1217430,
 1217431,
 1217432,
 1217433,
 1217434,
 1217428,
 1217436,
 1217437,
 1217438,
 1217439,
 1217440,
 1217441,
 3969954,
 1217442,
 1217443,
 1217444,
 1217445,
 1217446,
 3478439,
 1217447,
 1217448,
 3969963,
 1217449,
 1217450,
 1217451,
 1217452,
 1217453,
 1217454,
 1217455,
 1217456,
 1217457,
 1217458,
 1217459,
 1217460,
 1217461,
 1217462,
 1217463,
 1217464,
 1217465,
 1217466,
 1217467,
 1217469,
 1217470,
 1217471,
 1217468,
 1217473,
 824258,
 1217474,
 1217475,
 1217477,
 1217478,
 1217479,
 1217480,
 1217476,
 2331600,
 3773407,
 988147,
 1217525,
 988150,
 3445758,
 1217575,
 1217577,
 1217578,
 1217579,
 1840174,
 1840176,
 1840184,
 2659400,
 2659402,
 2659403,
 2659404,
 2659405,
 2659406,
 1217613,
 2659407,
 2659408,
 1217614,
 1217615,
 1217616,
 1217617,
 1217618,
 1217619,
 1217620,
 1217621,
 1021014,
 1217622,
 1217623,
 1217624,
 1021018,
 1217625,
 1217626,
 3576928,
 1217627,
 1217628,
 1217629,
 1217630,
 1217631,
 1217632,
 1217633,
 1217634,
 1217635,
 1217636,
 1217637,
 1217638,
 1217639,
 1217640,
 1217641,
 1217642,
 1217643,
 1217644,
 1217645,
 1217646,
 1217647,
 1217648,
 1217649,
 1217650,
 1217651,
 1217652,
 1217653,
 1217660,
 1217654,
 1217655,
 1217656,
 1217657,
 1217658,
 1217659,
 1217661,
 1217662,
 2331780,
 2331781,
 3576965,
 2331788,
 660634,
 1217693,
 988318,
 2266298,
 1021133,
 1021134,
 1021135,
 1021136,
 1021137,
 1021148,
 1217759,
 1217761,
 1217762,
 1217763,
 1021186,
 988419,
 1021219,
 1021238,
 857413,
 3544393,
 3151177,
 3151179,
 955721,
 955722,
 398667,
 955723,
 955724,
 955725,
 955726,
 1119584,
 3577190,
 1021288,
 3183981,
 1021303,
 3183993,
 1021320,
 1021321,
 3118476,
 3118483,
 1217944,
 3184039,
 1217962,
 3184049,
 2790842,
 1217991,
 2332103,
 1218000,
 2332113,
 2332114,
 988650,
 431598,
 726536,
 726538,
 2332172,
 2332173,
 2332174,
 2332175,
 2332177,
 2332178,
 2332179,
 2332182,
 2332184,
 2332191,
 2332192,
 3741226,
 726572,
 38447,
 3741233,
 1054269,
 2332226,
 726624,
 38538,
 988822,
 988843,
 2791090,
 2266809,
 2266810,
 2660039,
 956138,
 3446538,
 1701042,
 1546089,
 989056,
 2234240,
 1677213,
 2234276,
 2234279,
 2234281,
 2234284,
 989130,
 235474,
 2234390,
 2234393,
 2234394,
 2234395,
 3774492,
 989238,
 989239,
 2201667,
 2201668,
 2201669,
 2201670,
 2234444,
 563277,
 ...}

In [20]:
list(rel_dict.keys())

[6830,
 14608,
 2251,
 11971,
 4486,
 21992,
 2161,
 3933,
 5726,
 3044,
 18690,
 5352,
 24880,
 5563,
 3159,
 9872,
 4195,
 9998,
 4952,
 14057,
 4183,
 3528,
 4392,
 9988,
 6093,
 2564,
 2790,
 10164,
 4820,
 8131,
 3841,
 22709,
 4461,
 2791,
 10070,
 11214,
 4785,
 4272,
 14847,
 16111,
 9323,
 5246,
 5021,
 4548,
 4869,
 10054,
 7948,
 6162,
 5388,
 2551,
 7703,
 3170,
 2129,
 2459,
 6636,
 9030,
 4206,
 2487,
 4399,
 26300,
 3322,
 4703,
 2210,
 8655,
 5355,
 3579,
 20806,
 2856,
 23219,
 3337,
 7373,
 5818,
 2094,
 11309,
 6872,
 2990,
 2333,
 2877,
 4981,
 2840,
 2573,
 4376,
 29969,
 2375,
 13968,
 3223,
 2475,
 2316,
 10611,
 1941,
 3574,
 25442,
 22442,
 15448,
 5466,
 13700,
 5614,
 10663,
 5492,
 3771,
 7029,
 6082,
 5198,
 7845,
 4280,
 5921,
 15382,
 5453,
 17000,
 3531,
 15429,
 1999,
 10072,
 3299,
 4859,
 11896,
 6503,
 3272,
 4039,
 3485,
 12523,
 5310,
 12671,
 3087,
 17383,
 4802,
 6241,
 10520,
 23583,
 13642,
 1019,
 21573,
 1036,
 11125,
 7358,
 4046,
 13729,
 4824,
 2678,
 3247,
 21049,
 2860,
 2710,
 3733,
 4941,
 7152,
 8501,
 14423,
 7393,
 3902,
 22112,
 13630,
 2796,
 20552,
 8067,
 4028,
 7309,
 2858,
 3103,
 8132,
 3209,
 2591,
 14927,
 2485,
 4689,
 5565,
 7664,
 8278,
 2838,
 6726,
 29176,
 28165,
 3282,
 4012,
 4860,
 5047,
 9570,
 2347,
 5064,
 2769,
 4487,
 3878,
 24797,
 3386,
 23123,
 24904,
 4152,
 13900,
 2770,
 11181,
 4751,
 2616,
 4027,
 18722,
 3939,
 3724,
 24842,
 10485,
 14759,
 4622,
 4813,
 3395,
 19955,
 2447,
 2001,
 3903,
 5442,
 2495,
 7759,
 8774,
 12811,
 3688,
 2740,
 4213,
 4722,
 7891,
 22489,
 9630,
 3604,
 3455,
 10397,
 2436,
 5407,
 18976,
 27243,
 4794,
 6855,
 11166,
 5119,
 3959,
 9042,
 3224,
 9815,
 12725,
 2311,
 15748,
 3599,
 2351,
 3652,
 3415,
 9027,
 5298,
 15252,
 3425,
 3253,
 2428,
 3311,
 3308,
 5856,
 5376,
 2777,
 6960,
 15193,
 22284,
 2046,
 5128,
 7285,
 3879,
 3919,
 2960,
 3861,
 3362,
 13315,
 4793,
 7063,
 4271,
 5173,
 3148,
 7598,
 2455,
 5316,
 14218,
 18374,
 8802,
 14120,
 11679,
 3555,
 10962,
 5455,
 2285,
 3181,
 5658,
 7769,
 29683,
 2099,
 7311,
 6926,
 4433,
 9685,
 10021,
 17844,
 8087,
 2274,
 3036,
 2287,
 25570,
 5254,
 13449,
 3523,
 5005,
 17225,
 4615,
 7685,
 9597,
 3338,
 8853,
 9669,
 15138,
 6040,
 3596,
 3303,
 5880,
 20536,
 5735,
 19756,
 4585,
 20048,
 8383,
 2766,
 8525,
 1935,
 4576,
 3421,
 2687,
 4124,
 9603,
 8611,
 15440,
 11804,
 5597,
 9225,
 3614,
 14531,
 5899,
 7619,
 2503,
 15282,
 12709,
 18842,
 1024,
 22047,
 3655,
 5526,
 3154,
 10146,
 3605,
 9135,
 4625,
 10526,
 15687,
 3326,
 11995,
 7985,
 5481,
 8740,
 9526,
 9244,
 10787,
 16590,
 5413,
 3507,
 5934,
 14886,
 15349,
 6490,
 5676,
 4469,
 11466,
 5148,
 1005,
 18103,
 4704,
 2024,
 4899,
 8238,
 3165,
 2671,
 4443,
 3595,
 8078,
 14966,
 3726,
 7757,
 8630,
 18954,
 26113,
 13502,
 4733,
 4737,
 7437,
 3260,
 6574,
 6222,
 13302,
 7061,
 4907,
 2341,
 1921,
 4113,
 17097,
 3856,
 5367,
 2607,
 13276,
 22988,
 1928,
 4659,
 3065,
 8275,
 18798,
 3270,
 21616,
 3928,
 15347,
 2703,
 20660,
 3264,
 4061,
 4933,
 3081,
 7816,
 3696,
 5441,
 3451,
 6674,
 5038,
 18170,
 3817,
 18015,
 23266,
 12641,
 5467,
 10590,
 7142,
 2217,
 7150,
 6804,
 10414,
 2169,
 7000,
 5394,
 2697,
 3146,
 2899,
 5065,
 15408,
 18641,
 18369,
 9420,
 4561,
 19475,
 2223,
 5052,
 23976,
 5245,
 2213,
 3622,
 2481,
 11092,
 28711,
 24619,
 5333,
 3568,
 6111,
 53,
 9943,
 1943,
 18626,
 4248,
 3063,
 4949,
 5386,
 16028,
 16785,
 13601,
 5531,
 5251,
 8547,
 4905,
 23223,
 3940,
 6805,
 4300,
 2000,
 13153,
 7210,
 2921,
 23782,
 4863,
 3227,
 11867,
 18512,
 15365,
 9215,
 2057,
 2071,
 11619,
 6824,
 10270,
 17195,
 13838,
 9068,
 7514,
 6828,
 9821,
 5489,
 24821,
 4106,
 3547,
 4041,
 3681,
 18033,
 9094,
 3127,
 2544,
 7784,
 4963,
 26059,
 10533,
 12459,
 26829,
 6689,
 3760,
 7327,
 2031,
 14700,
 16470,
 4435,
 4101,
 7580,
 24252,
 4209,
 29629,
 7042,
 3259,
 22170,
 28004,
 29734,
 7728,
 4033,
 27802,
 16526,
 2875,
 28104,
 12214,
 20919,
 9300,
 14104,
 2535,
 6598,
 5996,
 10223,
 10124,
 30261,
 10761,
 6335,
 6634,
 11709,
 4671,
 16057,
 29514,
 7964,
 4086,
 4048,
 3298,
 3558,
 6161,
 11827,
 4088,
 15540,
 15924,
 4575,
 10960,
 4613,
 7742,
 4877,
 22957,
 8615,
 7191,
 11462,
 3500,
 9483,
 19166,
 5188,
 24612,
 22467,
 2199,
 16863,
 1016,
 28959,
 5945,
 2584,
 26768,
 5802,
 7268,
 25923,
 27287,
 16436,
 22331,
 6941,
 16324,
 2949,
 10975,
 5163,
 4050,
 4498,
 6882,
 3539,
 2712,
 8202,
 28273,
 23725,
 2261,
 13939,
 2625,
 4189,
 9124,
 9754,
 19043,
 5092,
 5328,
 12102,
 17452,
 17414,
 21195,
 4075,
 3951,
 3122,
 6879,
 20471,
 20152,
 26682,
 4067,
 5532,
 2322,
 24933,
 2140,
 1969,
 18409,
 23753,
 3347,
 25334,
 10180,
 11367,
 2650,
 13965,
 8166,
 28498,
 1025,
 15673,
 25368,
 2843,
 28853,
 6966,
 23483,
 22429,
 28936,
 10465,
 17616,
 15769,
 7897,
 19280,
 6876,
 4595,
 1009,
 24186,
 13672,
 3434,
 6497,
 2760,
 4003,
 5495,
 6647,
 4177,
 4541,
 5029,
 21843,
 5510,
 3554,
 4604,
 13040,
 8072,
 11655,
 10347,
 3426,
 5227,
 11093,
 19604,
 9976,
 13441,
 1023,
 1015,
 21677,
 6917,
 1022,
 17937,
 19259,
 20140,
 14520,
 4369,
 3584,
 2038,
 8773,
 12639,
 1918,
 2510,
 9914,
 10211,
 1012,
 2392,
 9407,
 26343,
 7663,
 3125,
 2722,
 5331,
 12222,
 4937,
 20711,
 21977,
 2748,
 11153,
 14183,
 14880,
 26276,
 12467,
 6201,
 2288,
 8641,
 14631,
 22318,
 3937,
 18621,
 14517,
 12386,
 11422,
 3699,
 11560,
 2039,
 26191,
 30391,
 2356,
 2244,
 3721,
 5398,
 12259,
 8059,
 17920,
 2565,
 2539,
 5209,
 26795,
 2880,
 18455,
 4103,
 7359,
 7834,
 5229,
 4293,
 9619,
 23891,
 8362,
 4194,
 12039,
 14560,
 3847,
 18141,
 10840,
 13095,
 13210,
 11260,
 16132,
 14675,
 3936,
 4407,
 3335,
 9378,
 6364,
 2792,
 10814,
 2890,
 5729,
 8016,
 3626,
 2601,
 21,
 5843,
 24010,
 22001,
 28404,
 2684,
 6025,
 3835,
 29486,
 23745,
 2526,
 15025,
 25,
 10229,
 2413,
 3038,
 3367,
 5579,
 2132,
 2868,
 8298,
 4472,
 13628,
 7447,
 7683,
 16439,
 25505,
 16794,
 5237,
 4666,
 10515,
 12334,
 22212,
 5016,
 4999,
 12516,
 28194,
 13204,
 9851,
 8056,
 6777,
 29788,
 28950,
 28393,
 14610,
 8188,
 2513,
 5232,
 11715,
 1997,
 4442,
 2085,
 17473,
 1006,
 6763,
 1008,
 7408,
 2290,
 6365,
 8366,
 10651,
 4997,
 7014,
 15428,
 6766,
 7521,
 9057,
 17980,
 6129,
 9507,
 3880,
 3374,
 21420,
 4297,
 9356,
 16944,
 18136,
 3892,
 14469,
 8463,
 10323,
 2642,
 2730,
 18471,
 4107,
 1954,
 4531,
 13255,
 5621,
 6678,
 7206,
 16557,
 6179,
 7418,
 12847,
 2961,
 8215,
 2752,
 13817,
 9390,
 22791,
 4322,
 14389,
 2828,
 8775,
 6551,
 15900,
 47,
 14576,
 6319,
 9680,
 10299,
 23509,
 7383,
 7872,
 29488,
 16225,
 6337,
 3484,
 6356,
 2905,
 25674,
 12438,
 11435,
 2297,
 20611,
 10096,
 24130,
 8375,
 6482,
 7560,
 22293,
 5024,
 14622,
 4881,
 4412,
 5512,
 4942,
 29272,
 9371,
 13104,
 13944,
 6119,
 8160,
 6728,
 20179,
 4430,
 20259,
 11394,
 7486,
 10216,
 16018,
 3373,
 2988,
 5397,
 16676,
 9155,
 5008,
 24364,
 24434,
 24386,
 1937,
 29545,
 9660,
 6985,
 14188,
 3848,
 6605,
 13033,
 1034,
 5039,
 20008,
 3414,
 2230,
 3508,
 2101,
 3384,
 11950,
 5077,
 3620,
 9267,
 27470,
 3852,
 5381,
 29815,
 4879,
 7446,
 5670,
 2156,
 6506,
 3753,
 7075,
 3867,
 3294,
 4284,
 2386,
 3123,
 6001,
 2502,
 6653,
 8359,
 4680,
 3286,
 8231,
 5321,
 6773,
 3769,
 2644,
 4714,
 16282,
 3777,
 15807,
 18737,
 8535,
 1960,
 ...]

In [21]:
(0, 1) == False

False

#### RELA

In [1]:
import pandas as pd

umls = pd.read_csv('UMLS_REL+RELA/UMLS_REL_hasDEF.csv')
umls

             CUI1                      REL      CUI2
0        C0000039                       AQ  C0001555
1        C0000039                       AQ  C0001688
2        C0000039                       AQ  C0002776
3        C0000039                       AQ  C0003139
4        C0000039                       AQ  C0005572
...           ...                      ...       ...
4206223  C5847615  pathological_process_of  C0443146
4206224  C5847622              inverse_isa  C0011854
4206225  C5847622              inverse_isa  C0271650
4206226  C5847622          finding_site_of  C0014136
4206227  C5847622  pathological_process_of  C0443146

[4206228 rows x 3 columns]

In [3]:
doc = pd.read_csv('UMLS_DOC.csv')[893:-1]
doc['VALUE'].tolist()

['AQ',
 'CHD',
 'DEL',
 'PAR',
 'QB',
 'RB',
 'RN',
 'RO',
 'RQ',
 'RU',
 'SUBX',
 'SY',
 'XR']

In [4]:
strings_to_check = doc['VALUE'].tolist()
mask = umls['REL'].str.contains('|'.join(strings_to_check))
filtered_df = umls[~mask]
filtered_df

             CUI1                      REL      CUI2
30       C0000039                mapped_to  C0216971
31       C0000039              inverse_isa  C0031610
32       C0000039                  same_as  C0216971
64       C0000052              inverse_isa  C0019495
66       C0000052             exhibited_by  C2256711
...           ...                      ...       ...
4206223  C5847615  pathological_process_of  C0443146
4206224  C5847622              inverse_isa  C0011854
4206225  C5847622              inverse_isa  C0271650
4206226  C5847622          finding_site_of  C0014136
4206227  C5847622  pathological_process_of  C0443146

[2592580 rows x 3 columns]

In [5]:
import pickle
with open('UMLS_NAME', 'rb') as fp:
    name_dict = pickle.load(fp)
with open('UMLS_REL', 'rb') as fp:
    rel_dict = pickle.load(fp)

from tqdm import tqdm
for i, row in tqdm(filtered_df.iterrows()):
    row['CUI1'] = name_dict[row['CUI1']]['name'][0]
    row['REL'] = rel_dict[row['REL']]
    row['CUI2'] = name_dict[row['CUI2']]['name'][0]
filtered_df

2592580it [02:49, 15273.30it/s]

,CUI1,REL,CUI2
30,Dipalmitoyllecithin,mapped to,colfosceril palmitate
31,Dipalmitoyllecithin,inverse is a,"Acid, Phosphatidic"
32,Dipalmitoyllecithin,same as,colfosceril palmitate
64,"1,4-alpha-D-Glucan:1,4-alpha-D-glucan 6-alpha-...",inverse is a,Hexosyltransferase
66,"1,4-alpha-D-Glucan:1,4-alpha-D-glucan 6-alpha-...",exhibited by,glycogen branching enzyme activity
...,...,...,...
4206223,Diabetes mellitus type 1 stage 2,pathological process of,Autoimmune reaction (finding)
4206224,Diabetes mellitus type 1 stage 3,inverse is a,Type I diabetes mellitus
4206225,Diabetes mellitus type 1 stage 3,inverse is a,diabetes chemical
4206226,Diabetes mellitus type 1 stage 3,finding site of,"Organ System, Endocrine/Metabolic"
4206227,Diabetes mellitus type 1 stage 3,pathological process of,Autoimmune reaction (finding)

In [8]:
filtered_df.to_csv('UMLS_REL+RELA/UMLS_RELA_posDEF.csv', index=False)

In [16]:
filtered_df[filtered_df['REL'] == 'is a']

,CUI1,REL,CUI2
215,alpha Naphthylamine,is a,2-naphthylamine
367,17-Hydroxycorticosteroids,is a,20alpha-Hydroxypregn-4-Ene-3-One
368,17-Hydroxycorticosteroids,is a,Pregnanetriol
369,17-Hydroxycorticosteroids,is a,17-alpha-hydroxyprogesterone
370,17-Hydroxycorticosteroids,is a,17-alpha-hydroxypregnanolone
...,...,...,...
4204162,Abnormal play,is a,Reduced imaginative play skills
4204164,Reduced imaginative play skills,is a,Reduced collaborative imaginative play
4204166,Nonfunctional or atypical use of objects in play,is a,Persistent preoccupation with parts of objects
4204172,Complete cleft of the upper lip,is a,Unilateral complete cleft lip (situation)
4204174,Microform cleft of the upper lip,is a,Microform unilateral cleft lip

In [17]:
filtered_df[filtered_df['REL'] == 'inverse is a']

,CUI1,REL,CUI2
31,Dipalmitoyllecithin,inverse is a,"Acid, Phosphatidic"
64,"1,4-alpha-D-Glucan:1,4-alpha-D-glucan 6-alpha-...",inverse is a,Hexosyltransferase
126,Isobutyltheophylline,inverse is a,Product containing phosphodiesterase inhibitor
151,MPTP,inverse is a,Dopamine Drugs
152,MPTP,inverse is a,Neurotoxins
...,...,...,...
4206217,Diabetes mellitus type 1 stage 1,inverse is a,Type I diabetes mellitus
4206220,Diabetes mellitus type 1 stage 2,inverse is a,Type I diabetes mellitus
4206221,Diabetes mellitus type 1 stage 2,inverse is a,diabetes chemical
4206224,Diabetes mellitus type 1 stage 3,inverse is a,Type I diabetes mellitus
4206225,Diabetes mellitus type 1 stage 3,inverse is a,diabetes chemical

In [19]:
import torch

a = torch.tensor([1, 2, 4], device='cuda')

filtered_df.iloc[a]

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [3]:
import numpy as np

I = np.load(f'PC_IPCA32_IVF_I10.npy').astype(np.int_)
D = np.load(f'PC_IPCA32_IVF_D10.npy')
I

array([[1805112, 3004680, 3675235, ..., 1805136, 3675196, 1727094],
       [1805112, 3004680, 3675235, ..., 1805136, 3675196, 1727094],
       [3913302, 3913303, 3020505, ..., 2387122,  839816, 1858945],
       ...,
       [3004664, 3004665, 1805091, ..., 4089421, 4089422, 1805120],
       [4014148, 2229574, 3051306, ..., 4014154, 3050288, 2813108],
       [ 521705,  568998,  429458, ..., 4013652, 3527580, 3527578]])

In [4]:
topk_idx_img = np.load(f'topk_idx_avg/topk_idx_img_PCTH_avg_HNSW.npy')
topk_idx_img

array([[ 721721,  721727, 2007427, ...,  721728, 1992983, 1993024],
       [ 721721,  721727, 2007427, ...,  721728, 1992983, 1993024],
       [3612265, 3361821, 3612340, ..., 3497578, 3612413, 3612319],
       ...,
       [ 525546, 1017410,  493166, ...,  648742,  486399,   73414],
       [3954175, 3451883, 3448507, ..., 4182122, 3787967, 3443937],
       [3898598, 4001548, 1524550, ..., 1623103, 3676946, 3016556]],
      dtype=int64)

In [38]:
import pandas as pd

df = pd.read_csv('UMLS_REL+RELA/UMLS_RELA_posDEF.csv', keep_default_na=False)
df.shape

(2592580, 3)

In [39]:
df[df['CUI1'] == 'Dose Form']

,CUI1,REL,CUI2
115095,Dose Form,use,capsules
115096,Dose Form,use,salve
115097,Dose Form,use,drug suppository
115098,Dose Form,use,Tablet dose form (qualifier value)
115099,Dose Form,use,Inh
115100,Dose Form,use,pill product
115101,Dose Form,is a,Bath additive (product)
115102,Dose Form,is a,Generator
115103,Dose Form,is a,Kit Dose Form
115104,Dose Form,is a,Unassigned Dose Form
115105,Dose Form,is a,NaN
115106,Dose Form,is a,Culture Dose Form
115107,Dose Form,is a,Drug Release Formulation
115108,Dose Form,is a,Conc
115109,Dose Form,is a,Pack Dosage Form
115110,Dose Form,is a,Procedure Dose Form
115111,Dose Form,is a,Exposure as Collected Dose Form
115112,Dose Form,is a,Veterinary Dosage Form
115113,Dose Form,is a,Anticoagulant and Preservative Solution for Bl...
115114,Dose Form,is a,Vaginal Delivery System Dosage Form
115115,Dose Form,is a,Live Animal Dosage Form
115116,Dose Form,inverse is a,Equipment
115117,Dose Form,subset includes concept,CDISC SDTM Terminology
115118,Dose Form,subset includes concept,CDISC SDTM Trial Summary Parameter Short Name ...
115119,Dose Form,subset includes concept,CDISC SDTM Trial Summary Parameter Long Name T...
115120,Dose Form,subset includes concept,CDISC Terminology
115121,Dose Form,subset includes concept,CDISC Root Variable Terminology
115122,Dose Form,subset includes concept,NCPDP Terminology
115123,Dose Form,subset includes concept,NCPDP Strength Form Terminology
115124,Dose Form,subset includes concept,CDISC Protocol Terminology
115125,Dose Form,subset includes concept,CDISC-GLOSSARY
115126,Dose Form,subset includes concept,CDISC Protocol Study Product Administration At...
115127,Dose Form,is a,Irrigant
115128,Dose Form,is a,Oral dosage form
115129,Dose Form,is a,Dental dose form
115130,Dose Form,is a,Otic dosage form
115131,Dose Form,is a,Parenteral drug preparation
115132,Dose Form,is a,Rectal dose form
115133,Dose Form,is a,Nasal dose form (dose form)
115134,Dose Form,is a,Vaginal dosage form (product)
115135,Dose Form,is a,Urethral dose form
115136,Dose Form,is a,Inhaler
115137,Dose Form,is a,Drug aerosol (qualifier value)
115138,Dose Form,is a,Spray dose form (qualifier value)
115139,Dose Form,is a,Basic dose form with solid state of matter
115140,Dose Form,is a,Liquid Dosage Form
115141,Dose Form,is a,Basic dose form with semi-solid state of matter
115142,Dose Form,is a,Transdermal drug delivery system
115143,Dose Form,is a,Gaseous dose form

In [26]:
df_cleaned = df[~df.map(lambda x: 'NA' == str(x)).any(axis=1)]
df_cleaned.shape

C:\Users\wxc\AppData\Local\Temp\ipykernel_7304\2806661452.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_cleaned = df[~df.applymap(lambda x: 'NA' == str(x)).any(axis=1)]

(2592558, 3)

In [27]:
df_cleaned[df_cleaned['CUI1'] == 'Dose Form']

,CUI1,REL,CUI2
115095,Dose Form,use,capsules
115096,Dose Form,use,salve
115097,Dose Form,use,drug suppository
115098,Dose Form,use,Tablet dose form (qualifier value)
115099,Dose Form,use,Inh
115100,Dose Form,use,pill product
115101,Dose Form,is a,Bath additive (product)
115102,Dose Form,is a,Generator
115103,Dose Form,is a,Kit Dose Form
115104,Dose Form,is a,Unassigned Dose Form
115106,Dose Form,is a,Culture Dose Form
115107,Dose Form,is a,Drug Release Formulation
115108,Dose Form,is a,Conc
115109,Dose Form,is a,Pack Dosage Form
115110,Dose Form,is a,Procedure Dose Form
115111,Dose Form,is a,Exposure as Collected Dose Form
115112,Dose Form,is a,Veterinary Dosage Form
115113,Dose Form,is a,Anticoagulant and Preservative Solution for Bl...
115114,Dose Form,is a,Vaginal Delivery System Dosage Form
115115,Dose Form,is a,Live Animal Dosage Form
115116,Dose Form,inverse is a,Equipment
115117,Dose Form,subset includes concept,CDISC SDTM Terminology
115118,Dose Form,subset includes concept,CDISC SDTM Trial Summary Parameter Short Name ...
115119,Dose Form,subset includes concept,CDISC SDTM Trial Summary Parameter Long Name T...
115120,Dose Form,subset includes concept,CDISC Terminology
115121,Dose Form,subset includes concept,CDISC Root Variable Terminology
115122,Dose Form,subset includes concept,NCPDP Terminology
115123,Dose Form,subset includes concept,NCPDP Strength Form Terminology
115124,Dose Form,subset includes concept,CDISC Protocol Terminology
115125,Dose Form,subset includes concept,CDISC-GLOSSARY
115126,Dose Form,subset includes concept,CDISC Protocol Study Product Administration At...
115127,Dose Form,is a,Irrigant
115128,Dose Form,is a,Oral dosage form
115129,Dose Form,is a,Dental dose form
115130,Dose Form,is a,Otic dosage form
115131,Dose Form,is a,Parenteral drug preparation
115132,Dose Form,is a,Rectal dose form
115133,Dose Form,is a,Nasal dose form (dose form)
115134,Dose Form,is a,Vaginal dosage form (product)
115135,Dose Form,is a,Urethral dose form
115136,Dose Form,is a,Inhaler
115137,Dose Form,is a,Drug aerosol (qualifier value)
115138,Dose Form,is a,Spray dose form (qualifier value)
115139,Dose Form,is a,Basic dose form with solid state of matter
115140,Dose Form,is a,Liquid Dosage Form
115141,Dose Form,is a,Basic dose form with semi-solid state of matter
115142,Dose Form,is a,Transdermal drug delivery system
115143,Dose Form,is a,Gaseous dose form

#### STAT

In [5]:
import nltk
import pandas as pd
# Define stopwords
stop_words = set(nltk.corpus.stopwords.words('english'))

# Function to compare two strings
def compare_strings(text, answer):
    # Tokenize strings into words
    text_words = set(nltk.word_tokenize(text.lower()))
    answer_words = set(nltk.word_tokenize(answer.lower()))

    # Remove stopwords from answer words
    answer_words_without_stopwords = answer_words - stop_words

    # Check if all remaining words in answer appear in text
    if answer_words_without_stopwords.issubset(text_words):
        return True
    else:
        return False

# Function to check if answer is a substring of text
def is_substring(answer, text):
    return answer in text

df = pd.read_csv('../SOURCE/PMC-VQA/test_clean.csv')
# jsonl = pd.read_json('llava_json_data/PC_avg_IVFPQ/test_clean_answer_top1_img.jsonl', lines=True)
jsonl = pd.read_json('llava_json_data/test_clean_answer_32top3_img.jsonl', lines=True)
# jsonl = pd.read_json('llava_json_data/test-clean-answer.jsonl', lines=True)
jsonl['answer'] = df['Answer']
jsonl['question'] = df['Question']

js = pd.read_json('llava_json_data/test-clean-answer.jsonl', lines=True)
js['answer'] = df['Answer']
js['question'] = df['Question']

In [60]:
cl = []
# keywords = ['cancer', 'tumor', 'tumour', 'leukemi', 'carcino', 'lymphoma', 'glioma', 'astrocytoma', 'adenoma',
#             'cholangiocarcinoma', 'chondrosarcoma', 'ependymoma', 'sarcoma', 'melanoma', 'mesothelioma', 'myeloma',
#             'neoplas', 'blastoma', 'meningioma', 'thymoma', 'papilloma', 'pheochromocytoma']

# keywords = ['artery', 'vein', 'blood', 'platelet', 'erythrocyte']

# keywords = ['immune',
#             'marrow', 'thymus', 'lymph', 'spleen', 'tonsil',
#             'leukocyte', 'neutrophil', 'eosinophil', 'basophil', 'monocyte', 'macrophage', 'dendritic cell', 'microglia cell', 'B cell', 'T cell', 'antibod', 'antigen',
#             'complement ', 'cytokines ', 'HLA']

# keywords = ['mri', 'mri scan', 'mri image', 'mri images', 'conventional mri', 'magnetic resonance imaging', 'magnetic resonance imaging (mri)',
#             't1-weighted', 't1-weighted image', 't1-weighted images', 't2-weighted', 't2-weighted image', 't2-weighted images',
#             'diffusion-weighted', 'diffusion-weighted image', 'diffusion-weighted images',
#             'flair', 'flair image', 'flair images',
#             ]

keywords = [' ct', ' ct ', ' ct.', ' ct scan', ' ct image', 'ct images', 'computed tomography', '3dct', '3dct image', '3dct images', 'cat scan', ' ctca ', ' cbct ']

# keywords = ['x-ray', 'x-rays', 'x-ray image', 'x-ray images', 'chest x-ray',]

# keywords = ['ultrasound', 'ultrasound image', 'ultrasound images', 'ultrasonography', 'ultrasound (us)', 'color doppler']

# keywords = ['sem', 'sem image', 'sem images',
#             'tem', 'tem image', 'tem images', 'hr-tem', 'hr-tem image', 'hr-tem images']

cl.append(jsonl[jsonl['question'].str.contains(f'(?:{"|".join(keywords)})', case=False)])
cl.append(jsonl[jsonl['answer'].str.contains(f'(?:{"|".join(keywords)})', case=False)])
cl.append(jsonl[jsonl['answer'].str.contains('^ct scan$', case=False)])

new = pd.concat(cl).sort_index()
new

,question_id,prompt,text,answer_id,model_id,metadata,answer,question
13,PMC8415998_F1,The retrieved background knowledge is given as...,Assistant: The imaging technique used in this ...,Qq8VPCrtEdxniykZVNwUNC,/scratch/xwu20/LLMs/llava-med,{},Computed tomography,What imaging technique was used in this study?
15,PMC8416005_F2,The retrieved background knowledge is given as...,Assistant: The abdominal CT scan showed no abn...,nnX9pSmhL3tCt4iCZRubV5,/scratch/xwu20/LLMs/llava-med,{},Acute hepatitis,What was the result of the abdominal CT in op...
16,PMC8416005_F2,The retrieved background knowledge is given as...,Assistant: The abdominal CT image revealed hyd...,WXbTe2ErwpeujhqMvSh2wQ,/scratch/xwu20/LLMs/llava-med,{},Acute hepatitis,What did the abdominal CT reveal in option A?
19,PMC8416045_F9,The retrieved background knowledge is given as...,Assistant: The figure displays MRI images of t...,QzpumzogVV85QFcdt9uJTt,/scratch/xwu20/LLMs/llava-med,{},MRI and CT,What kind of images are displayed on the left...
44,PMC8416487_FIG3,The retrieved background knowledge is given as...,Assistant: The imaging modality used to obtain...,8mdEioP7roDTbqBTHg83DZ,/scratch/xwu20/LLMs/llava-med,{},CT scan,What imaging modality was used to obtain these...
...,...,...,...,...,...,...,...,...
1869,PMC8927646_F2,The retrieved background knowledge is given as...,Assistant: The purple arrow on the CT image at...,UEVxVA5xSo7nqv7g7zV8LF,/scratch/xwu20/LLMs/llava-med,{},Inflammatory changes in the descending part of...,What did the purple arrow on the CT image ind...
1873,PMC8928079_f0015,The retrieved background knowledge is given as...,Assistant: The imaging technique used in this ...,Ax9BqShJNrCMLkwF9agP5P,/scratch/xwu20/LLMs/llava-med,{},CT scan,What is the name of the imaging technique used...
1890,PMC8930273_fig2,The retrieved background knowledge is given as...,Assistant: The imaging technique used for this...,fji5mB8SXLaeAy6TxJ8o47,/scratch/xwu20/LLMs/llava-med,{},CT scan,What imaging technique was used for this image?
1937,PMC8157460_Fig1,The retrieved background knowledge is given as...,Assistant: The imaging modality used to obtain...,WVkd2orNiM3s9uFswgWSfC,/scratch/xwu20/LLMs/llava-med,{},CT scan,Which imaging modality was used to obtain imag...
1979,PMC8160441_F1,The retrieved background knowledge is given as...,Assistant: The figure includes axial T1-weight...,izYMRawNVoWnjgcstrBGUZ,/scratch/xwu20/LLMs/llava-med,{},Computed tomography imaging,What type of images are shown in the figure?

In [63]:
# Iterate over each row of the DataFrame
count = 0
idx_list = []
for i, row in new.iterrows():
    text = row['text'].lower()
    answer = row['answer'].lower()
    if compare_strings(text, answer):
        count += 1
        idx_list.append(i)

print(count / len(new) * 100)
print(len(idx_list))

18.064516129032256
28

In [79]:
check = new.loc[idx_list]
i = 15
print(check.loc[idx_list[i], 'prompt'])
print(check.loc[idx_list[i], 'answer'])

The retrieved background knowledge is given as follows: ether degradation is a diorcinol breakdown. down-regulation of cell wall biogenesis, MAPKKK cascade negatively regulated by cell integrity MAPK pathway. positive regulation of cellular component biogenesis is a upregulation of heterochromatin formation. Cell Movement Process gene product plays role in biological process PIERCE2 protein, human. Please answer the question: What could be the cause of the lateral displacement seen in the CT scan?
<image>
Brain injury

In [6]:
# Iterate over each row of the DataFrame
count = 0
jsonl_list = []
for i, row in jsonl.iterrows():
    text = row['text'].lower()
    answer = row['answer'].lower()
    if compare_strings(text, answer):
        count += 1
        jsonl_list.append(i)

print(count / len(jsonl) * 100)
print(len(jsonl_list))

13.5
270

In [7]:
# Iterate over each row of the DataFrame
count = 0
js_list = []
for i, row in js.iterrows():
    text = row['text'].lower()
    answer = row['answer'].lower()
    if compare_strings(text, answer):
        count += 1
        js_list.append(i)

print(count / len(js) * 100)
print(len(js_list))

14.499999999999998
290

In [8]:
difference = [item for item in jsonl_list if item not in js_list]
difference

[19,
 20,
 27,
 28,
 86,
 117,
 123,
 153,
 157,
 182,
 190,
 194,
 209,
 213,
 221,
 291,
 381,
 386,
 444,
 487,
 494,
 530,
 544,
 674,
 682,
 706,
 768,
 778,
 834,
 836,
 847,
 852,
 891,
 927,
 968,
 974,
 991,
 1020,
 1027,
 1050,
 1054,
 1157,
 1164,
 1190,
 1195,
 1202,
 1204,
 1230,
 1236,
 1250,
 1289,
 1325,
 1342,
 1351,
 1389,
 1402,
 1415,
 1417,
 1498,
 1504,
 1514,
 1522,
 1542,
 1569,
 1579,
 1585,
 1608,
 1625,
 1654,
 1657,
 1667,
 1697,
 1728,
 1732,
 1744,
 1762,
 1830,
 1891,
 1892,
 1911,
 1919,
 1924,
 1926,
 1964,
 1965]

In [25]:
check = jsonl.loc[difference]
i = 13
print(check.loc[difference[i], 'question_id'])
print(check.loc[difference[i], 'prompt'])
print(check.loc[difference[i], 'text'])
print(check.loc[difference[i], 'answer'])

PMC8422719_Fig3
The retrieved background knowledge is given as follows: Right Salpingo-Oophorectomy excised anatomy has procedure Fallopian tube, NOS. Lipoma of Spermatic Cord associated morphology of Tumors. Primitive reflexes (palmomental, snout, glabellar) is a Persistent nutritive suckle swallow. Please answer the question: What was the growth pattern of the tumor cells observed on the H&E stain?
<image>
Assistant: The growth pattern of the tumor cells observed on the H&E stain was not predominantly papillary. Instead, the tumor formed an exophytic mass of papillary-like projections.
Papillary growth pattern